In [1]:
import polars as pl
import time

In [2]:
import polars as pl

inicial = (
    pl.scan_parquet(r"C:\Users\diogo.durao\Documents\covid_rj.parquet")
    .with_columns(
        pl.col("paciente_idade").cast(pl.Int64, strict=False),
        pl.col("paciente_dataNascimento").str.to_date("%Y-%m-%d", strict=False),
        pl.col("vacina_dataAplicacao").str.to_date("%Y-%m-%d", strict=False)
    )
)

display(inicial.collect().head())

shape: (5, 32)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ document_ ┆ paciente_ ┆ paciente_ ┆ paciente_ ┆ … ┆ vacina_de ┆ vacina_co ┆ vacina_no ┆ sistema_ │
│ id        ┆ id        ┆ idade     ┆ dataNasci ┆   ┆ scricao_d ┆ digo      ┆ me        ┆ origem   │
│ ---       ┆ ---       ┆ ---       ┆ mento     ┆   ┆ ose       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ i64       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ str      │
│           ┆           ┆           ┆ date      ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 436b4b52- ┆ 333ec2c1d ┆ 60        ┆ 1963-12-1 ┆ … ┆ Única     ┆ 33        ┆ INF3      ┆ Novo PNI │
│ 1e20-41b0 ┆ 748f880e6 ┆           ┆ 4         ┆   ┆           ┆           ┆           ┆          │
│ -bc2b-0a2 ┆ 1248eece8 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ e4b…      ┆ c06…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ d2a4632a- ┆ 67e6e5bd9 ┆ 70        ┆ 1951-11-0 ┆ … ┆ Reforço   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│ 9906-4d9d ┆ 1f070cac6 ┆           ┆ 1         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -9e37-239 ┆ 62d36f014 ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ fee…      ┆ 84f…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 436be4ab- ┆ ec0c97786 ┆ 41        ┆ 1980-01-0 ┆ … ┆ Reforço   ┆ 88        ┆ COVID-19  ┆ Novo PNI │
│ 8b6b-4517 ┆ 2379ec1e6 ┆           ┆ 3         ┆   ┆           ┆           ┆ JANSSEN - ┆          │
│ -984e-e3b ┆ cb1da87ee ┆           ┆           ┆   ┆           ┆           ┆ Ad26.COV2 ┆          │
│ 3af…      ┆ d27…      ┆           ┆           ┆   ┆           ┆           ┆ .S        ┆          │
│ d2a529c8- ┆ bd8a7396d ┆ 26        ┆ 1995-04-1 ┆ … ┆ 2ª Dose   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│ 9a07-4b70 ┆ cae6088da ┆           ┆ 7         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -ad71-e9b ┆ 675334005 ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 864…      ┆ 798…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 436d60f1- ┆ c0bd4a543 ┆ 24        ┆ 1997-09-0 ┆ … ┆ 2ª Dose   ┆ 85        ┆ COVID-19  ┆ Novo PNI │
│ c035-469c ┆ 181499599 ┆           ┆ 4         ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│ -929d-a5a ┆ 04e7ce5da ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│ d86…      ┆ 15a…      ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [3]:
# Filtro Simples: Apenas pacientes do Acre
q_ac = inicial.filter(
    pl.col("paciente_endereco_uf") == "AC"
)

# Filtro Composto: Acre e idade maior que 60
q_ac_idosos = inicial.filter(
    (pl.col("paciente_endereco_uf") == "AC") &
    (pl.col("paciente_idade") > 60)
)

# Filtro com Lista: Apenas AC e AP
q_estados = inicial.filter(
    pl.col("paciente_endereco_uf").is_in(["AC", "AP"])
)

display(q_ac.collect())
display(q_ac_idosos.collect())
display(q_estados.collect())

shape: (866, 32)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ document_ ┆ paciente_ ┆ paciente_ ┆ paciente_ ┆ … ┆ vacina_de ┆ vacina_co ┆ vacina_no ┆ sistema_ │
│ id        ┆ id        ┆ idade     ┆ dataNasci ┆   ┆ scricao_d ┆ digo      ┆ me        ┆ origem   │
│ ---       ┆ ---       ┆ ---       ┆ mento     ┆   ┆ ose       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ i64       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ str      │
│           ┆           ┆           ┆ date      ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 75d64d74- ┆ ad995b991 ┆ 5         ┆ 2016-11-0 ┆ … ┆ 2ª Dose   ┆ 99        ┆ COVID-19  ┆ Novo PNI │
│ 7379-41c9 ┆ f043ddc3a ┆           ┆ 3         ┆   ┆           ┆           ┆ PEDIÁTRIC ┆          │
│ -8808-ae1 ┆ 749ee94bd ┆           ┆           ┆   ┆           ┆           ┆ A -       ┆          │
│ 033…      ┆ 9c4…      ┆           ┆           ┆   ┆           ┆           ┆ PFIZER C… ┆          │
│ a567d7e7- ┆ 03c2a7e7a ┆ 5         ┆ 2017-06-2 ┆ … ┆ 1ª Dose   ┆ 87        ┆ COVID-19  ┆ ESUS APS │
│ 89f6-45d8 ┆ 83bc07e9b ┆           ┆ 3         ┆   ┆           ┆           ┆ PFIZER -  ┆ -        │
│ -a97c-3fd ┆ bb81272e2 ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆ NACIONAL │
│ aae…      ┆ 4f1…      ┆           ┆           ┆   ┆           ┆           ┆           ┆ (OFFLINE │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ )        │
│ b628ad6d- ┆ 4a4824577 ┆ 34        ┆ 1987-09-2 ┆ … ┆ Reforço   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│ 1fd2-46a5 ┆ 14b3d8aba ┆           ┆ 8         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -9102-b10 ┆ c768eb223 ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ bd6…      ┆ 1c9…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ cec1d0da- ┆ 61642fb93 ┆ 27        ┆ 1995-07-1 ┆ … ┆ Dose      ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│ cefc-4f6d ┆ 5017b6b21 ┆           ┆ 3         ┆   ┆ Adicional ┆           ┆ PFIZER -  ┆          │
│ -a8c7-9c2 ┆ 4e6ea28c5 ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 6f8…      ┆ ae1…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 8e3c531b- ┆ 64349f67f ┆ 62        ┆ 1958-08-2 ┆ … ┆ 1ª Dose   ┆ 85        ┆ COVID-19  ┆ Novo PNI │
│ 4731-4bb1 ┆ 12859637f ┆           ┆ 1         ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│ -87e4-d77 ┆ 9ff2f9ec2 ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│ 973…      ┆ 660…      ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 24ebd0c1- ┆ e3dd60e15 ┆ 5         ┆ 2017-05-1 ┆ … ┆ 1ª Dose   ┆ 99        ┆ COVID-19  ┆ Novo PNI │
│ e048-4803 ┆ 3cb1fb3cf ┆           ┆ 3         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -85c9-ae6 ┆ 70d2604b9 ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 3b6…      ┆ 93f…      ┆           ┆           ┆   ┆           ┆           ┆ PE…       ┆          │
│ 4c4bb9ff- ┆ bed5bde86 ┆ 63        ┆ 1958-01-1 ┆ … ┆ Reforço   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│ 5647-42f9 ┆ 5d7d4aa7e ┆           ┆ 5         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -a9a8-350 ┆ ca04309d4 ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ a5e…      ┆ d09…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 6157b7c6- ┆ 3b82725b8 ┆ 61        ┆ 1960-02-0 ┆ … ┆ Reforço   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│ 7de4-4c6d ┆ 84eef5f29 ┆           ┆ 7         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -9b80-3d7 ┆ 291a4d0d5 ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ ea9…      ┆ b65…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9be20df4- ┆ 82c0a41bd ┆ 34        ┆ 1988-09-0 ┆ … ┆ Reforço   ┆ 103       ┆ COVID-19  ┆ Novo PNI │
│ b730-4d8a ┆ 5e18a0366 ┆           ┆ 2         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -bbc3-679 ┆ 980861ef4 ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 8c4…      ┆ c04…      ┆           ┆           ┆   ┆           ┆           ┆ BI…       ┆          │
│ a639ee3a- ┆ d72086888 ┆ 29        ┆ 1992-01-0 ┆ … ┆ 1ª Dose   ┆ 86        ┆ COVID-19  ┆ Novo PNI │
│ 0a8c-4c64 ┆ 2e14c455b ┆           ┆ 9         ┆   ┆           ┆           ┆ SINOVAC/B ┆          │
│ -9fc6-88c ┆ 059e334b5 ┆           ┆           ┆   ┆           ┆           ┆ UTANTAN - ┆          │
│ 912…      ┆ dc6…      ┆           ┆           ┆   ┆           ┆           ┆ CO…       ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

shape: (133, 32)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ document_ ┆ paciente_ ┆ paciente_ ┆ paciente_ ┆ … ┆ vacina_de ┆ vacina_co ┆ vacina_no ┆ sistema_ │
│ id        ┆ id        ┆ idade     ┆ dataNasci ┆   ┆ scricao_d ┆ digo      ┆ me        ┆ origem   │
│ ---       ┆ ---       ┆ ---       ┆ mento     ┆   ┆ ose       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ i64       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ str      │
│           ┆           ┆           ┆ date      ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 8e3c531b- ┆ 64349f67f ┆ 62        ┆ 1958-08-2 ┆ … ┆ 1ª Dose   ┆ 85        ┆ COVID-19  ┆ Novo PNI │
│ 4731-4bb1 ┆ 12859637f ┆           ┆ 1         ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│ -87e4-d77 ┆ 9ff2f9ec2 ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│ 973…      ┆ 660…      ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
│ e9c59fde- ┆ 6b8722b7b ┆ 78        ┆ 1943-06-0 ┆ … ┆ Dose      ┆ 85        ┆ COVID-19  ┆ Novo PNI │
│ c581-40af ┆ 8f0bd6b0c ┆           ┆ 6         ┆   ┆ Adicional ┆           ┆ ASTRAZENE ┆          │
│ -af00-fcb ┆ 7035729e1 ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│ 694…      ┆ beb…      ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
│ 77b7924c- ┆ 45d2177db ┆ 62        ┆ 1958-09-1 ┆ … ┆ 2ª Dose   ┆ 85        ┆ COVID-19  ┆ Novo PNI │
│ f2e1-43b0 ┆ 24ae3b543 ┆           ┆ 8         ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│ -9a43-07d ┆ bee31d825 ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│ 2a5…      ┆ c29…      ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
│ 23e30e26- ┆ a2732f137 ┆ 62        ┆ 1960-06-0 ┆ … ┆ Reforço   ┆ 103       ┆ COVID-19  ┆ Novo PNI │
│ f5fc-4e52 ┆ c27c2bff0 ┆           ┆ 3         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -b2c4-de4 ┆ ef27729a4 ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 3a9…      ┆ 960…      ┆           ┆           ┆   ┆           ┆           ┆ BI…       ┆          │
│ f6354cb2- ┆ db5e27af4 ┆ 67        ┆ 1954-04-2 ┆ … ┆ 2ª Dose   ┆ 86        ┆ COVID-19  ┆ Novo PNI │
│ 3798-4c56 ┆ 3d07f9844 ┆           ┆ 6         ┆   ┆           ┆           ┆ SINOVAC/B ┆          │
│ -b47f-452 ┆ 6726608f1 ┆           ┆           ┆   ┆           ┆           ┆ UTANTAN - ┆          │
│ 0e6…      ┆ 7d4…      ┆           ┆           ┆   ┆           ┆           ┆ CO…       ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 8ce1608a- ┆ 1a75eb919 ┆ 64        ┆ 1957-04-3 ┆ … ┆ Reforço   ┆ 85        ┆ COVID-19  ┆ Novo PNI │
│ b7b4-4958 ┆ 0f13f3510 ┆           ┆ 0         ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│ -ab80-c77 ┆ 2ba88b9f6 ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│ 014…      ┆ f48…      ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
│ dc052f06- ┆ 32a1f53ba ┆ 76        ┆ 1948-03-2 ┆ … ┆ Única     ┆ 33        ┆ INF3      ┆ Novo PNI │
│ f8f3-4378 ┆ a9f7e9f73 ┆           ┆ 2         ┆   ┆           ┆           ┆           ┆          │
│ -83de-4cf ┆ aa136e4e7 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ e2d…      ┆ 079…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2390019e- ┆ a404d5069 ┆ 89        ┆ 1931-09-1 ┆ … ┆ 2ª Dose   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│ d7c6-418c ┆ fad35eb4c ┆           ┆ 7         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -9892-6f7 ┆ c34bff781 ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 537…      ┆ 7a4…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4c4bb9ff- ┆ bed5bde86 ┆ 63        ┆ 1958-01-1 ┆ … ┆ Reforço   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│ 5647-42f9 ┆ 5d7d4aa7e ┆           ┆ 5         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -a9a8-350 ┆ ca04309d4 ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ a5e…      ┆ d09…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 6157b7c6- ┆ 3b82725b8 ┆ 61        ┆ 1960-02-0 ┆ … ┆ Reforço   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│ 7de4-4c6d ┆ 84eef5f29 ┆           ┆ 7         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -9b80-3d7 ┆ 291a4d0d5 ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ ea9…      ┆ b65…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

shape: (1_489, 32)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ document_ ┆ paciente_ ┆ paciente_ ┆ paciente_ ┆ … ┆ vacina_de ┆ vacina_co ┆ vacina_no ┆ sistema_ │
│ id        ┆ id        ┆ idade     ┆ dataNasci ┆   ┆ scricao_d ┆ digo      ┆ me        ┆ origem   │
│ ---       ┆ ---       ┆ ---       ┆ mento     ┆   ┆ ose       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ i64       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ str      │
│           ┆           ┆           ┆ date      ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 6467175c- ┆ 4fd895c67 ┆ 15        ┆ 2005-11-2 ┆ … ┆ 2ª Dose   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│ 6200-4e0d ┆ f09f91e78 ┆           ┆ 1         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -9a30-7fb ┆ 734c748eb ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 763…      ┆ 8d8…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 75d64d74- ┆ ad995b991 ┆ 5         ┆ 2016-11-0 ┆ … ┆ 2ª Dose   ┆ 99        ┆ COVID-19  ┆ Novo PNI │
│ 7379-41c9 ┆ f043ddc3a ┆           ┆ 3         ┆   ┆           ┆           ┆ PEDIÁTRIC ┆          │
│ -8808-ae1 ┆ 749ee94bd ┆           ┆           ┆   ┆           ┆           ┆ A -       ┆          │
│ 033…      ┆ 9c4…      ┆           ┆           ┆   ┆           ┆           ┆ PFIZER C… ┆          │
│ 7c239afd- ┆ 4184aa223 ┆ 24        ┆ 1997-11-2 ┆ … ┆ Reforço   ┆ 85        ┆ COVID-19  ┆ Novo PNI │
│ 3f7c-4855 ┆ e7ac26694 ┆           ┆ 5         ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│ -8f1b-f9c ┆ 5b0b519a4 ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│ 007…      ┆ de4…      ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
│ 2cec66ae- ┆ 435103ba2 ┆ 37        ┆ 1983-10-2 ┆ … ┆ 1ª Dose   ┆ 89        ┆ COVID-19  ┆ Novo PNI │
│ ef7e-41ce ┆ bea82f036 ┆           ┆ 2         ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│ -aba0-bf3 ┆ 734098fe1 ┆           ┆           ┆   ┆           ┆           ┆ CA -      ┆          │
│ ecc…      ┆ 108…      ┆           ┆           ┆   ┆           ┆           ┆ ChAdOx1…  ┆          │
│ a1377fc7- ┆ 6c76c94d7 ┆ 23        ┆ 1998-07-0 ┆ … ┆ 1ª Dose   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│ dbe8-4d84 ┆ aba0c50b1 ┆           ┆ 6         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -86ef-84f ┆ 8cacb421b ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 65e…      ┆ 4d7…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 6157b7c6- ┆ 3b82725b8 ┆ 61        ┆ 1960-02-0 ┆ … ┆ Reforço   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│ 7de4-4c6d ┆ 84eef5f29 ┆           ┆ 7         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -9b80-3d7 ┆ 291a4d0d5 ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ ea9…      ┆ b65…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9be20df4- ┆ 82c0a41bd ┆ 34        ┆ 1988-09-0 ┆ … ┆ Reforço   ┆ 103       ┆ COVID-19  ┆ Novo PNI │
│ b730-4d8a ┆ 5e18a0366 ┆           ┆ 2         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -bbc3-679 ┆ 980861ef4 ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 8c4…      ┆ c04…      ┆           ┆           ┆   ┆           ┆           ┆ BI…       ┆          │
│ a639ee3a- ┆ d72086888 ┆ 29        ┆ 1992-01-0 ┆ … ┆ 1ª Dose   ┆ 86        ┆ COVID-19  ┆ Novo PNI │
│ 0a8c-4c64 ┆ 2e14c455b ┆           ┆ 9         ┆   ┆           ┆           ┆ SINOVAC/B ┆          │
│ -9fc6-88c ┆ 059e334b5 ┆           ┆           ┆   ┆           ┆           ┆ UTANTAN - ┆          │
│ 912…      ┆ dc6…      ┆           ┆           ┆   ┆           ┆           ┆ CO…       ┆          │
│ bca8e8d8- ┆ 437e91031 ┆ 20        ┆ 2001-05-0 ┆ … ┆ 2ª Dose   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│ 0a9d-4885 ┆ 3e5982a92 ┆           ┆ 3         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -9123-8cb ┆ 6ac58033a ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 3d3…      ┆ 442…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 06437f07- ┆ 3a8e8b119 ┆ 7         ┆ 2014-06-1 ┆ … ┆ 1ª Dose   ┆ 99        ┆ COVID-19  ┆ Novo PNI │
│ 337e-45f6 ┆ c2081c14a ┆           ┆ 2         ┆   ┆           ┆           ┆ PEDIÁTRIC ┆          │
│ -a74f-74e ┆ 527aabfc9 ┆           ┆           ┆   ┆           ┆           ┆ A -       ┆          │
│ 7ed…      ┆ 62d…      ┆           ┆           ┆   ┆           ┆           ┆ PFIZER C… ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [4]:
# Selecionar apenas colunas importantes
q_simples = inicial.select([
    "paciente_endereco_uf",
    "paciente_endereco_nmMunicipio",
    "paciente_idade",
    "vacina_nome",
    "vacina_dataAplicacao"
])

# Remover colunas menos úteis/pesadas
q_sem_codigos = inicial.drop([
    "document_id",
    "paciente_id"
])

# Seleciona tudo EXCETO as colunas listadas
q_sem_codigos = inicial.select(
    pl.exclude([
        "document_id",
        "paciente_id"
    ])
)

display(q_simples.collect())
display(q_sem_codigos.collect())

shape: (9_764_498, 5)
┌────────────────────┬────────────────────┬────────────────┬───────────────────┬───────────────────┐
│ paciente_endereco_ ┆ paciente_endereco_ ┆ paciente_idade ┆ vacina_nome       ┆ vacina_dataAplica │
│ uf                 ┆ nmMunicipio        ┆ ---            ┆ ---               ┆ cao               │
│ ---                ┆ ---                ┆ i64            ┆ str               ┆ ---               │
│ str                ┆ str                ┆                ┆                   ┆ date              │
╞════════════════════╪════════════════════╪════════════════╪═══════════════════╪═══════════════════╡
│ RJ                 ┆ SAO GONCALO        ┆ 60             ┆ INF3              ┆ 2024-06-20        │
│ RJ                 ┆ CAMPOS DOS         ┆ 70             ┆ COVID-19 PFIZER - ┆ 2021-11-11        │
│                    ┆ GOYTACAZES         ┆                ┆ COMIRNATY         ┆                   │
│ RJ                 ┆ RIO DE JANEIRO     ┆ 41             ┆ COVID-19 JANSSEN  ┆ 2021-12-13        │
│                    ┆                    ┆                ┆ - Ad26.COV2.S     ┆                   │
│ RJ                 ┆ BELFORD ROXO       ┆ 26             ┆ COVID-19 PFIZER - ┆ 2021-10-21        │
│                    ┆                    ┆                ┆ COMIRNATY         ┆                   │
│ RJ                 ┆ CAMPOS DOS         ┆ 24             ┆ COVID-19 ASTRAZEN ┆ 2021-09-28        │
│                    ┆ GOYTACAZES         ┆                ┆ ECA/FIOCRUZ -…    ┆                   │
│ …                  ┆ …                  ┆ …              ┆ …                 ┆ …                 │
│ RJ                 ┆ RIO DE JANEIRO     ┆ 74             ┆ COVID-19 MODERNA  ┆ 2024-07-03        │
│                    ┆                    ┆                ┆ - SPIKEVAX        ┆                   │
│ RJ                 ┆ ITATIAIA           ┆ 34             ┆ COVID-19          ┆ 2021-03-12        │
│                    ┆                    ┆                ┆ SINOVAC/BUTANTAN  ┆                   │
│                    ┆                    ┆                ┆ - CO…             ┆                   │
│ RJ                 ┆ RIO DE JANEIRO     ┆ 32             ┆ COVID-19 ASTRAZEN ┆ 2021-05-27        │
│                    ┆                    ┆                ┆ ECA/FIOCRUZ -…    ┆                   │
│ RJ                 ┆ NOVA FRIBURGO      ┆ 67             ┆ COVID-19 ASTRAZEN ┆ 2021-04-13        │
│                    ┆                    ┆                ┆ ECA/FIOCRUZ -…    ┆                   │
│ RJ                 ┆ RIO DE JANEIRO     ┆ 68             ┆ INF3              ┆ 2024-03-25        │
└────────────────────┴────────────────────┴────────────────┴───────────────────┴───────────────────┘

shape: (9_764_498, 30)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ paciente_ ┆ paciente_ ┆ paciente_ ┆ paciente_ ┆ … ┆ vacina_de ┆ vacina_co ┆ vacina_no ┆ sistema_ │
│ idade     ┆ dataNasci ┆ enumSexoB ┆ racaCor_c ┆   ┆ scricao_d ┆ digo      ┆ me        ┆ origem   │
│ ---       ┆ mento     ┆ iologico  ┆ odigo     ┆   ┆ ose       ┆ ---       ┆ ---       ┆ ---      │
│ i64       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ str      │
│           ┆ date      ┆ str       ┆ str       ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 60        ┆ 1963-12-1 ┆ F         ┆ 99        ┆ … ┆ Única     ┆ 33        ┆ INF3      ┆ Novo PNI │
│           ┆ 4         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 70        ┆ 1951-11-0 ┆ F         ┆ 02        ┆ … ┆ Reforço   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 41        ┆ 1980-01-0 ┆ M         ┆ 99        ┆ … ┆ Reforço   ┆ 88        ┆ COVID-19  ┆ Novo PNI │
│           ┆ 3         ┆           ┆           ┆   ┆           ┆           ┆ JANSSEN - ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Ad26.COV2 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ .S        ┆          │
│ 26        ┆ 1995-04-1 ┆ M         ┆ 03        ┆ … ┆ 2ª Dose   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│           ┆ 7         ┆           ┆           ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 24        ┆ 1997-09-0 ┆ F         ┆ 04        ┆ … ┆ 2ª Dose   ┆ 85        ┆ COVID-19  ┆ Novo PNI │
│           ┆ 4         ┆           ┆           ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 74        ┆ 1949-11-0 ┆ F         ┆ 03        ┆ … ┆ Dose      ┆ 97        ┆ COVID-19  ┆ Novo PNI │
│           ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆ MODERNA - ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ SPIKEVAX  ┆          │
│ 34        ┆ 1986-06-0 ┆ F         ┆ 99        ┆ … ┆ 1ª Dose   ┆ 86        ┆ COVID-19  ┆ Novo PNI │
│           ┆ 5         ┆           ┆           ┆   ┆           ┆           ┆ SINOVAC/B ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ UTANTAN - ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ CO…       ┆          │
│ 32        ┆ 1988-12-1 ┆ M         ┆ 01        ┆ … ┆ 1ª Dose   ┆ 85        ┆ COVID-19  ┆ Novo PNI │
│           ┆ 5         ┆           ┆           ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
│ 67        ┆ 1953-07-1 ┆ F         ┆ 01        ┆ … ┆ 1ª Dose   ┆ 85        ┆ COVID-19  ┆ Novo PNI │
│           ┆ 8         ┆           ┆           ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
│ 68        ┆ 1956-02-1 ┆ F         ┆ 03        ┆ … ┆ Única     ┆ 33        ┆ INF3      ┆ Novo PNI │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
# Categorizar faixa etária
q_categoria = inicial.with_columns(
    pl.when(pl.col("paciente_idade") >= 60)
    .then(pl.lit("Idoso"))
    .when(pl.col("paciente_idade") >= 18)
    .then(pl.lit("Adulto"))
    .otherwise(pl.lit("Menor de Idade"))
    .alias("FAIXA_ETARIA")
)

display(
    q_categoria.select([
        "paciente_idade",
        "FAIXA_ETARIA"
    ]).collect()
)

shape: (9_764_498, 2)
┌────────────────┬──────────────┐
│ paciente_idade ┆ FAIXA_ETARIA │
│ ---            ┆ ---          │
│ i64            ┆ str          │
╞════════════════╪══════════════╡
│ 60             ┆ Idoso        │
│ 70             ┆ Idoso        │
│ 41             ┆ Adulto       │
│ 26             ┆ Adulto       │
│ 24             ┆ Adulto       │
│ …              ┆ …            │
│ 74             ┆ Idoso        │
│ 34             ┆ Adulto       │
│ 32             ┆ Adulto       │
│ 67             ┆ Idoso        │
│ 68             ┆ Idoso        │
└────────────────┴──────────────┘

In [6]:
# Análise por faixa etária
q_analise_categoria = (
    q_categoria
    .group_by("FAIXA_ETARIA")
    .agg([
        pl.len().alias("total_pessoas"),
        pl.col("paciente_idade").mean().alias("media_idade"),
        pl.col("paciente_idade").min().alias("menor_idade"),
        pl.col("paciente_idade").max().alias("maior_idade")
    ])
    .sort("media_idade", descending=True)
)

display(q_analise_categoria.collect())

shape: (3, 5)
┌────────────────┬───────────────┬─────────────┬─────────────┬─────────────┐
│ FAIXA_ETARIA   ┆ total_pessoas ┆ media_idade ┆ menor_idade ┆ maior_idade │
│ ---            ┆ ---           ┆ ---         ┆ ---         ┆ ---         │
│ str            ┆ u32           ┆ f64         ┆ i64         ┆ i64         │
╞════════════════╪═══════════════╪═════════════╪═════════════╪═════════════╡
│ Idoso          ┆ 2590486       ┆ 70.378487   ┆ 60          ┆ 128         │
│ Adulto         ┆ 5964833       ┆ 39.000719   ┆ 18          ┆ 59          │
│ Menor de Idade ┆ 1209179       ┆ 10.335229   ┆ 0           ┆ 17          │
└────────────────┴───────────────┴─────────────┴─────────────┴─────────────┘

In [7]:
# Pegar as primeiras 10 linhas
q_head = inicial.head(10)

# Pegar da linha 100 até a 150
q_meio = inicial.slice(100, 50)

display(q_head.collect())
display(q_meio.collect())

shape: (10, 32)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ document_ ┆ paciente_ ┆ paciente_ ┆ paciente_ ┆ … ┆ vacina_de ┆ vacina_co ┆ vacina_no ┆ sistema_ │
│ id        ┆ id        ┆ idade     ┆ dataNasci ┆   ┆ scricao_d ┆ digo      ┆ me        ┆ origem   │
│ ---       ┆ ---       ┆ ---       ┆ mento     ┆   ┆ ose       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ i64       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ str      │
│           ┆           ┆           ┆ date      ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 436b4b52- ┆ 333ec2c1d ┆ 60        ┆ 1963-12-1 ┆ … ┆ Única     ┆ 33        ┆ INF3      ┆ Novo PNI │
│ 1e20-41b0 ┆ 748f880e6 ┆           ┆ 4         ┆   ┆           ┆           ┆           ┆          │
│ -bc2b-0a2 ┆ 1248eece8 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ e4b…      ┆ c06…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ d2a4632a- ┆ 67e6e5bd9 ┆ 70        ┆ 1951-11-0 ┆ … ┆ Reforço   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│ 9906-4d9d ┆ 1f070cac6 ┆           ┆ 1         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -9e37-239 ┆ 62d36f014 ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ fee…      ┆ 84f…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 436be4ab- ┆ ec0c97786 ┆ 41        ┆ 1980-01-0 ┆ … ┆ Reforço   ┆ 88        ┆ COVID-19  ┆ Novo PNI │
│ 8b6b-4517 ┆ 2379ec1e6 ┆           ┆ 3         ┆   ┆           ┆           ┆ JANSSEN - ┆          │
│ -984e-e3b ┆ cb1da87ee ┆           ┆           ┆   ┆           ┆           ┆ Ad26.COV2 ┆          │
│ 3af…      ┆ d27…      ┆           ┆           ┆   ┆           ┆           ┆ .S        ┆          │
│ d2a529c8- ┆ bd8a7396d ┆ 26        ┆ 1995-04-1 ┆ … ┆ 2ª Dose   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│ 9a07-4b70 ┆ cae6088da ┆           ┆ 7         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -ad71-e9b ┆ 675334005 ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 864…      ┆ 798…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 436d60f1- ┆ c0bd4a543 ┆ 24        ┆ 1997-09-0 ┆ … ┆ 2ª Dose   ┆ 85        ┆ COVID-19  ┆ Novo PNI │
│ c035-469c ┆ 181499599 ┆           ┆ 4         ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│ -929d-a5a ┆ 04e7ce5da ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│ d86…      ┆ 15a…      ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
│ d2a616fb- ┆ ded99239a ┆ 67        ┆ 1954-09-2 ┆ … ┆ 2º        ┆ 88        ┆ COVID-19  ┆ Novo PNI │
│ a27e-4657 ┆ 002b11b89 ┆           ┆ 1         ┆   ┆ Reforço   ┆           ┆ JANSSEN - ┆          │
│ -ae90-045 ┆ 308aad802 ┆           ┆           ┆   ┆           ┆           ┆ Ad26.COV2 ┆          │
│ ffe…      ┆ 0e9…      ┆           ┆           ┆   ┆           ┆           ┆ .S        ┆          │
│ 436e377f- ┆ 7f992f281 ┆ 63        ┆ 1958-06-2 ┆ … ┆ Reforço   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│ 2d82-4efc ┆ 410338c77 ┆           ┆ 8         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -b950-a38 ┆ 2e6abe230 ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 946…      ┆ c92…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ d2a87ce2- ┆ 7c2c55e79 ┆ 24        ┆ 1996-12-1 ┆ … ┆ 2ª Dose   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│ ab67-42e3 ┆ 5dc01badd ┆           ┆ 9         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -a68a-5df ┆ cbf6d00af ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 164…      ┆ 0c2…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 436efc74- ┆ b56668d88 ┆ 53        ┆ 1967-07-0 ┆ … ┆ 1ª Dose   ┆ 85        ┆ COVID-19  ┆ Novo PNI │
│ 9770-4d00 ┆ 1871a8a61 ┆           ┆ 7         ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│ -804a-5cb ┆ 3ccc546cc ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│ 57c…      ┆ d14…      ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
│ d2a936e7- ┆ 7f05b86b6 ┆ 31        ┆ 1991-03-0 ┆ … ┆ Reforço   ┆ 85        ┆ COVID-19  ┆ Novo PNI │
│ 5ea0-43ef ┆ a7ac99e7d ┆           ┆ 5         ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│ -a06f-6dd ┆ 64edd2b15 ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│ 474…      ┆ bfb…      ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

shape: (50, 32)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ document_ ┆ paciente_ ┆ paciente_ ┆ paciente_ ┆ … ┆ vacina_de ┆ vacina_co ┆ vacina_no ┆ sistema_ │
│ id        ┆ id        ┆ idade     ┆ dataNasci ┆   ┆ scricao_d ┆ digo      ┆ me        ┆ origem   │
│ ---       ┆ ---       ┆ ---       ┆ mento     ┆   ┆ ose       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ i64       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ str      │
│           ┆           ┆           ┆ date      ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 43ae7d1e- ┆ 33fc14ecc ┆ 48        ┆ 1973-05-1 ┆ … ┆ 1ª Dose   ┆ 89        ┆ COVID-19  ┆ Novo PNI │
│ 6807-4edc ┆ 20585cd88 ┆           ┆ 1         ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│ -9262-586 ┆ b392723ac ┆           ┆           ┆   ┆           ┆           ┆ CA -      ┆          │
│ a1d…      ┆ 236…      ┆           ┆           ┆   ┆           ┆           ┆ ChAdOx1…  ┆          │
│ d2dd8fe7- ┆ c1f966824 ┆ 25        ┆ 1996-06-0 ┆ … ┆ 1ª Dose   ┆ 86        ┆ COVID-19  ┆ Novo PNI │
│ 632d-44a4 ┆ 71a2af3bb ┆           ┆ 1         ┆   ┆           ┆           ┆ SINOVAC/B ┆          │
│ -b3a5-d26 ┆ de809c952 ┆           ┆           ┆   ┆           ┆           ┆ UTANTAN - ┆          │
│ 850…      ┆ 7b0…      ┆           ┆           ┆   ┆           ┆           ┆ CO…       ┆          │
│ 43b021be- ┆ 49b5e2b77 ┆ 56        ┆ 1965-05-0 ┆ … ┆ 2ª Dose   ┆ 85        ┆ COVID-19  ┆ Novo PNI │
│ 90b5-4c57 ┆ 2ff69f605 ┆           ┆ 7         ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│ -844c-93d ┆ 8d6711673 ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│ 6f3…      ┆ fea…      ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
│ d2dfc70a- ┆ d55266034 ┆ 54        ┆ 1967-08-0 ┆ … ┆ Reforço   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│ 91a6-40bc ┆ ac887048d ┆           ┆ 3         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -b535-7a8 ┆ ea6dab4bf ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ df0…      ┆ 2dc…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 43b0da9c- ┆ b92af121c ┆ 48        ┆ 1973-11-2 ┆ … ┆ Reforço   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│ fbe6-4c49 ┆ a1d1d14d8 ┆           ┆ 3         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -8dc5-505 ┆ 7c69e56f1 ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 1fe…      ┆ 772…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ d2fdfc87- ┆ bf5b5b00e ┆ 63        ┆ 1958-10-3 ┆ … ┆ Reforço   ┆ 85        ┆ COVID-19  ┆ Novo PNI │
│ d3ba-4460 ┆ 3a679322e ┆           ┆ 1         ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│ -ad85-187 ┆ 2384067c4 ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│ 9c8…      ┆ 6b0…      ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
│ 43c54e86- ┆ 933b49897 ┆ 74        ┆ 1947-07-1 ┆ … ┆ Reforço   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│ b9a9-4517 ┆ c36ae3783 ┆           ┆ 2         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -886f-59f ┆ d4dbf7695 ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 17c…      ┆ dd1…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ d2fe6265- ┆ baa48abff ┆ 60        ┆ 1961-11-1 ┆ … ┆ Reforço   ┆ 85        ┆ COVID-19  ┆ Novo PNI │
│ c9a3-4753 ┆ a08ea7daf ┆           ┆ 1         ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│ -913d-980 ┆ ea04e048b ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│ 787…      ┆ d83…      ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
│ 43c5b249- ┆ ba0217663 ┆ 36        ┆ 1985-05-2 ┆ … ┆ 2ª Dose   ┆ 85        ┆ COVID-19  ┆ Novo PNI │
│ b843-4778 ┆ e00ad82fb ┆           ┆ 5         ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│ -9d6f-700 ┆ 9e3deed89 ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│ ef3…      ┆ 925…      ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
│ d2fe9d42- ┆ e4a35c78b ┆ 32        ┆ 1991-12-1 ┆ … ┆ Única     ┆ 33        ┆ INF3      ┆ Novo PNI │
│ bdea-4f9a ┆ 02ffbdeb4 ┆           ┆ 4         ┆   ┆           ┆           ┆           ┆          │
│ -b6db-b66 ┆ b0dcf3365 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ b68…      ┆ a1e…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [8]:
# Recorte de linhas específicas
q_recorte_indices = (
    inicial
    .with_row_index("id_linha")
    .filter(pl.col("id_linha").is_in([0, 10, 50]))
    .select([
        "paciente_endereco_uf",
        "paciente_endereco_nmMunicipio"
    ])
)

display(q_recorte_indices.collect())

shape: (3, 2)
┌──────────────────────┬───────────────────────────────┐
│ paciente_endereco_uf ┆ paciente_endereco_nmMunicipio │
│ ---                  ┆ ---                           │
│ str                  ┆ str                           │
╞══════════════════════╪═══════════════════════════════╡
│ RJ                   ┆ SAO GONCALO                   │
│ RJ                   ┆ NOVA FRIBURGO                 │
│ RJ                   ┆ PETROPOLIS                    │
└──────────────────────┴───────────────────────────────┘

In [9]:
q_stats_mun = (
    inicial.group_by("paciente_endereco_nmMunicipio")
    .agg([
        pl.len().alias("total_vacinados"),
        pl.col("paciente_idade").mean().alias("media_idade"),
        pl.col("paciente_idade").max().alias("maior_idade"),
        pl.col("paciente_endereco_uf").first().alias("uf_origem")
    ])
    .sort("total_vacinados", descending=True)
)

display(q_stats_mun.collect())

shape: (4_722, 5)
┌───────────────────────────────┬─────────────────┬─────────────┬─────────────┬───────────┐
│ paciente_endereco_nmMunicipio ┆ total_vacinados ┆ media_idade ┆ maior_idade ┆ uf_origem │
│ ---                           ┆ ---             ┆ ---         ┆ ---         ┆ ---       │
│ str                           ┆ u32             ┆ f64         ┆ i64         ┆ str       │
╞═══════════════════════════════╪═════════════════╪═════════════╪═════════════╪═══════════╡
│ RIO DE JANEIRO                ┆ 4287364         ┆ 44.644223   ┆ 128         ┆ RJ        │
│ SAO GONCALO                   ┆ 473894          ┆ 44.168593   ┆ 124         ┆ RJ        │
│ DUQUE DE CAXIAS               ┆ 416043          ┆ 41.541889   ┆ 112         ┆ RJ        │
│ NOVA IGUACU                   ┆ 354168          ┆ 42.728742   ┆ 121         ┆ RJ        │
│ NITEROI                       ┆ 295141          ┆ 47.207064   ┆ 124         ┆ RJ        │
│ …                             ┆ …               ┆ …           ┆ …           ┆ …         │
│ GALIA                         ┆ 1               ┆ 23.0        ┆ 23          ┆ SP        │
│ FONTE BOA                     ┆ 1               ┆ 32.0        ┆ 32          ┆ AM        │
│ CORDILHEIRA ALTA              ┆ 1               ┆ 33.0        ┆ 33          ┆ SC        │
│ LOBATO                        ┆ 1               ┆ 30.0        ┆ 30          ┆ PR        │
│ Centro                        ┆ 1               ┆ 35.0        ┆ 35          ┆           │
└───────────────────────────────┴─────────────────┴─────────────┴─────────────┴───────────┘

In [10]:
import polars as pl
import time

print("=== TESTE 1: Processamento SEM StringCache ===")
start_1 = time.time()

q_sem_cache = (
    pl.scan_parquet(r"C:\Users\diogo.durao\Documents\covid_rj.parquet")
    .with_columns(
        pl.col("paciente_idade").cast(pl.Int64, strict=False),
        pl.col("paciente_dataNascimento").str.to_date("%Y-%m-%d", strict=False),
        pl.col("vacina_dataAplicacao").str.to_date("%Y-%m-%d", strict=False)
    )
    .group_by(["paciente_endereco_uf", "paciente_endereco_nmMunicipio"])
    .agg([
        pl.col("paciente_idade").mean().alias("media_idade"),
        pl.col("paciente_idade").std().alias("desvio_idade")
    ])
    .sort("media_idade", descending=True)
)

df_1 = q_sem_cache.collect()
end_1 = time.time()
tempo_sem = end_1 - start_1

print(f"Tempo SEM Cache: {tempo_sem:.4f} segundos")
print(f"Uso de memória estimado (coluna UF): {df_1['paciente_endereco_uf'].estimated_size()} bytes\n")

display(df_1)

=== TESTE 1: Processamento SEM StringCache ===
Tempo SEM Cache: 0.9569 segundos
Uso de memória estimado (coluna UF): 9892 bytes

shape: (4_955, 4)
┌──────────────────────┬───────────────────────────────┬─────────────┬──────────────┐
│ paciente_endereco_uf ┆ paciente_endereco_nmMunicipio ┆ media_idade ┆ desvio_idade │
│ ---                  ┆ ---                           ┆ ---         ┆ ---          │
│ str                  ┆ str                           ┆ f64         ┆ f64          │
╞══════════════════════╪═══════════════════════════════╪═════════════╪══════════════╡
│ MT                   ┆ ALTO PARAGUAI                 ┆ 92.5        ┆ 2.12132      │
│ TO                   ┆ CASEARA                       ┆ 92.0        ┆ null         │
│ MS                   ┆ CORGUINHO                     ┆ 91.333333   ┆ 0.57735      │
│ GO                   ┆ CAVALCANTE                    ┆ 90.0        ┆ 19.79899     │
│ PR                   ┆ KALORE                        ┆ 89.0        ┆ null         │
│ …                    ┆ …                             ┆ …           ┆ …            │
│ BA                   ┆ IUIU                          ┆ 4.0         ┆ null         │
│ GO                   ┆ ARENOPOLIS                    ┆ 4.0         ┆ null         │
│ RS                   ┆ GRAMADO DOS LOUREIROS         ┆ 3.0         ┆ null         │
│ MG                   ┆ CONCEICAO DAS PEDRAS          ┆ 2.0         ┆ null         │
│ PR                   ┆ JARDIM ALEGRE                 ┆ 2.0         ┆ null         │
└──────────────────────┴───────────────────────────────┴─────────────┴──────────────┘

In [12]:
print("=== TESTE 2: Processamento COM StringCache ===")

with pl.StringCache():
    start_2 = time.time()

    q_com_cache = (
        pl.scan_parquet(r"C:\Users\diogo.durao\Documents\covid_rj.parquet")
        .with_columns(
            pl.col("paciente_idade").cast(pl.Int64, strict=False),
            pl.col("paciente_dataNascimento").str.to_date("%Y-%m-%d", strict=False),
            pl.col("vacina_dataAplicacao").str.to_date("%Y-%m-%d", strict=False)
        )
        .group_by([
            "paciente_endereco_uf",
            "paciente_endereco_nmMunicipio"
        ])
        .agg([
            pl.col("paciente_idade").mean().alias("media_idade"),
            pl.col("paciente_idade").std().alias("desvio_idade")
        ])
        .sort("media_idade", descending=True)
    )

    df_2 = q_com_cache.collect()
    end_2 = time.time()

tempo_com = end_2 - start_2

print(f"Tempo COM Cache: {tempo_com:.4f} segundos")
print(f"Uso de memória estimado (coluna UF): {df_2['paciente_endereco_uf'].estimated_size()} bytes\n")

=== TESTE 2: Processamento COM StringCache ===
Tempo COM Cache: 0.9011 segundos
Uso de memória estimado (coluna UF): 9892 bytes