In [1]:
import polars as pl
import time

In [2]:
import polars as pl

inicial = (
    pl.scan_parquet(r"C:\Users\Usuario\OneDrive\Documentos\Covid_AP.parquet")
    .with_columns(
        pl.col("paciente_idade").cast(pl.Int64, strict=False),
        pl.col("paciente_dataNascimento").str.to_date("%Y-%m-%d", strict=False),
        pl.col("vacina_dataAplicacao").str.to_date("%Y-%m-%d", strict=False)
    )
)

display(inicial.collect().head())

shape: (5, 32)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ document_ ┆ paciente_ ┆ paciente_ ┆ paciente_ ┆ … ┆ vacina_de ┆ vacina_co ┆ vacina_no ┆ sistema_ │
│ id        ┆ id        ┆ idade     ┆ dataNasci ┆   ┆ scricao_d ┆ digo      ┆ me        ┆ origem   │
│ ---       ┆ ---       ┆ ---       ┆ mento     ┆   ┆ ose       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ i64       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ str      │
│           ┆           ┆           ┆ date      ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 485d7c3e- ┆ 8863c1423 ┆ 1         ┆ 2022-09-0 ┆ … ┆ Única     ┆ 33        ┆ INF3      ┆ Novo PNI │
│ ae77-4f2b ┆ 83a7fdf28 ┆           ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│ -9d49-f4c ┆ 847ae8187 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 897…      ┆ c36…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ b29481b6- ┆ 200a51a7a ┆ 40        ┆ 1981-07-2 ┆ … ┆ 2ª Dose   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│ 8f40-465f ┆ e9ad13bfb ┆           ┆ 6         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -bb6d-723 ┆ 0ffcb26df ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ d63…      ┆ 858…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 486a03d9- ┆ 967654cd9 ┆ 1         ┆ 2022-05-2 ┆ … ┆ 2ª Dose   ┆ 102       ┆ COVID-19  ┆ Novo PNI │
│ e333-424b ┆ 8da34327f ┆           ┆ 9         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -b5d1-f69 ┆ cadd37a88 ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 395…      ┆ aad…      ┆           ┆           ┆   ┆           ┆           ┆ PE…       ┆          │
│ acabdab4- ┆ 22282860c ┆ 41        ┆ 1982-12-0 ┆ … ┆ Única     ┆ 33        ┆ INF3      ┆ Novo PNI │
│ 73d6-43c7 ┆ 138ceda2c ┆           ┆ 2         ┆   ┆           ┆           ┆           ┆          │
│ -b514-117 ┆ 04266afe5 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 053…      ┆ eba…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 48d451ac- ┆ ae0eb283f ┆ 25        ┆ 1996-11-0 ┆ … ┆ Reforço   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│ c089-4c24 ┆ 5261e384c ┆           ┆ 4         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -b381-856 ┆ 682ed616c ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ a64…      ┆ 0a8…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [3]:
# Filtro Simples: Apenas pacientes do Acre
q_ac = inicial.filter(
    pl.col("paciente_endereco_uf") == "AC"
)

# Filtro Composto: Acre e idade maior que 60
q_ac_idosos = inicial.filter(
    (pl.col("paciente_endereco_uf") == "AC") &
    (pl.col("paciente_idade") > 60)
)

# Filtro com Lista: Apenas AC e AP
q_estados = inicial.filter(
    pl.col("paciente_endereco_uf").is_in(["AC", "AP"])
)

display(q_ac.collect())
display(q_ac_idosos.collect())
display(q_estados.collect())

shape: (51, 32)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ document_ ┆ paciente_ ┆ paciente_ ┆ paciente_ ┆ … ┆ vacina_de ┆ vacina_co ┆ vacina_no ┆ sistema_ │
│ id        ┆ id        ┆ idade     ┆ dataNasci ┆   ┆ scricao_d ┆ digo      ┆ me        ┆ origem   │
│ ---       ┆ ---       ┆ ---       ┆ mento     ┆   ┆ ose       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ i64       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ str      │
│           ┆           ┆           ┆ date      ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 7210680a- ┆ 13c340890 ┆ 42        ┆ 1978-03-0 ┆ … ┆ 2ª Dose   ┆ 86        ┆ COVID-19  ┆ Novo PNI │
│ 107b-444d ┆ 14e812fcd ┆           ┆ 1         ┆   ┆           ┆           ┆ SINOVAC/B ┆          │
│ -ae5c-ac8 ┆ 59962b06b ┆           ┆           ┆   ┆           ┆           ┆ UTANTAN - ┆          │
│ 7bb…      ┆ aa8…      ┆           ┆           ┆   ┆           ┆           ┆ CO…       ┆          │
│ f92281e6- ┆ 87596911d ┆ 33        ┆ 1987-06-2 ┆ … ┆ 1ª Dose   ┆ 86        ┆ COVID-19  ┆ Novo PNI │
│ 0481-47d7 ┆ f160f15a6 ┆           ┆ 3         ┆   ┆           ┆           ┆ SINOVAC/B ┆          │
│ -b063-d54 ┆ b9f4a11ac ┆           ┆           ┆   ┆           ┆           ┆ UTANTAN - ┆          │
│ e9c…      ┆ 866…      ┆           ┆           ┆   ┆           ┆           ┆ CO…       ┆          │
│ b4a5e99c- ┆ 0f3dcfac7 ┆ 52        ┆ 1968-08-2 ┆ … ┆ 1ª Dose   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│ 332b-43b0 ┆ 75f67b484 ┆           ┆ 0         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -8dfb-b74 ┆ ccd011317 ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 277…      ┆ 9b4…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 8ef5455c- ┆ 7174ac04d ┆ 20        ┆ 2000-12-2 ┆ … ┆ 2ª Dose   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│ a677-4469 ┆ 81b474840 ┆           ┆ 8         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -adc6-478 ┆ 99f7b3431 ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 317…      ┆ 38f…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ c82952f0- ┆ d3f87ffc4 ┆ 24        ┆ 1997-09-1 ┆ … ┆ 2ª Dose   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│ 1c37-4d19 ┆ 5e5437361 ┆           ┆ 6         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -98d7-896 ┆ d85b43baa ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ b64…      ┆ 45c…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ a6f7e716- ┆ d734ad792 ┆ 52        ┆ 1969-11-2 ┆ … ┆ Reforço   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│ db20-418e ┆ 3cef6b70d ┆           ┆ 2         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -ae86-0a6 ┆ 405a8b222 ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 75e…      ┆ eac…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4b87df8f- ┆ 2ff8de57b ┆ 31        ┆ 1989-06-0 ┆ … ┆ 1ª Dose   ┆ 85        ┆ COVID-19  ┆ Novo PNI │
│ 74c7-413a ┆ 5abfbbd7f ┆           ┆ 7         ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│ -8f04-408 ┆ 8ea557e19 ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│ 7f7…      ┆ 9e9…      ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
│ 09bd2821- ┆ d3f87ffc4 ┆ 23        ┆ 1997-09-1 ┆ … ┆ 1ª Dose   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│ 251b-4e95 ┆ 5e5437361 ┆           ┆ 6         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -a3ca-e33 ┆ d85b43baa ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 109…      ┆ 45c…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 80ff8ad6- ┆ d7bb3759a ┆ 28        ┆ 1993-05-2 ┆ … ┆ 2ª Dose   ┆ 85        ┆ COVID-19  ┆ Novo PNI │
│ 346c-4c1e ┆ a5f3567eb ┆           ┆ 8         ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│ -a0d5-7f8 ┆ 3038f9d2f ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│ 3ad…      ┆ 4d6…      ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
│ 3eec8083- ┆ 2dab386a5 ┆ 64        ┆ 1957-04-0 ┆ … ┆ 2ª Dose   ┆ 85        ┆ COVID-19  ┆ Novo PNI │
│ f305-4750 ┆ f89ea0f64 ┆           ┆ 7         ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│ -904d-6b2 ┆ 31405e0fd ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│ 785…      ┆ 507…      ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

shape: (8, 32)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ document_ ┆ paciente_ ┆ paciente_ ┆ paciente_ ┆ … ┆ vacina_de ┆ vacina_co ┆ vacina_no ┆ sistema_ │
│ id        ┆ id        ┆ idade     ┆ dataNasci ┆   ┆ scricao_d ┆ digo      ┆ me        ┆ origem   │
│ ---       ┆ ---       ┆ ---       ┆ mento     ┆   ┆ ose       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ i64       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ str      │
│           ┆           ┆           ┆ date      ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ cb6775d8- ┆ fc6af82a5 ┆ 85        ┆ 1935-04-1 ┆ … ┆ 1ª Dose   ┆ 86        ┆ COVID-19  ┆ Novo PNI │
│ c311-4bd5 ┆ 489995d16 ┆           ┆ 5         ┆   ┆           ┆           ┆ SINOVAC/B ┆          │
│ -ad5c-e8b ┆ b33929e8a ┆           ┆           ┆   ┆           ┆           ┆ UTANTAN - ┆          │
│ b7d…      ┆ 36b…      ┆           ┆           ┆   ┆           ┆           ┆ CO…       ┆          │
│ 60598c99- ┆ fc6af82a5 ┆ 85        ┆ 1935-04-1 ┆ … ┆ 2ª Dose   ┆ 86        ┆ COVID-19  ┆ Novo PNI │
│ 739e-4e11 ┆ 489995d16 ┆           ┆ 5         ┆   ┆           ┆           ┆ SINOVAC/B ┆          │
│ -9419-76d ┆ b33929e8a ┆           ┆           ┆   ┆           ┆           ┆ UTANTAN - ┆          │
│ f9a…      ┆ 36b…      ┆           ┆           ┆   ┆           ┆           ┆ CO…       ┆          │
│ b6c1e0d1- ┆ d61c4d69b ┆ 67        ┆ 1953-08-0 ┆ … ┆ 1ª Dose   ┆ 86        ┆ COVID-19  ┆ Novo PNI │
│ 9219-4203 ┆ 106a731d1 ┆           ┆ 7         ┆   ┆           ┆           ┆ SINOVAC/B ┆          │
│ -9fbe-2d9 ┆ d157c77cd ┆           ┆           ┆   ┆           ┆           ┆ UTANTAN - ┆          │
│ b02…      ┆ f27…      ┆           ┆           ┆   ┆           ┆           ┆ CO…       ┆          │
│ cd92b26a- ┆ fc6af82a5 ┆ 87        ┆ 1935-04-1 ┆ … ┆ Reforço   ┆ 103       ┆ COVID-19  ┆ Novo PNI │
│ aee8-4787 ┆ 489995d16 ┆           ┆ 5         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -a368-afc ┆ b33929e8a ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 56a…      ┆ 36b…      ┆           ┆           ┆   ┆           ┆           ┆ BI…       ┆          │
│ b40e0a9e- ┆ 02bc54387 ┆ 80        ┆ 1940-11-2 ┆ … ┆ 2ª Dose   ┆ 85        ┆ COVID-19  ┆ Novo PNI │
│ eec8-4dba ┆ 00cd5d393 ┆           ┆ 7         ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│ -a859-d18 ┆ 3f614509e ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│ afc…      ┆ 522…      ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
│ 58f78e4e- ┆ 895dd0836 ┆ 83        ┆ 1937-12-0 ┆ … ┆ 2ª Dose   ┆ 86        ┆ COVID-19  ┆ Novo PNI │
│ 0d6e-4761 ┆ 2adfd5b3e ┆           ┆ 1         ┆   ┆           ┆           ┆ SINOVAC/B ┆          │
│ -89c8-440 ┆ 0deebb159 ┆           ┆           ┆   ┆           ┆           ┆ UTANTAN - ┆          │
│ fa0…      ┆ 921…      ┆           ┆           ┆   ┆           ┆           ┆ CO…       ┆          │
│ 353fb7aa- ┆ d61c4d69b ┆ 67        ┆ 1953-08-0 ┆ … ┆ 2ª Dose   ┆ 86        ┆ COVID-19  ┆ Novo PNI │
│ e3d5-4806 ┆ 106a731d1 ┆           ┆ 7         ┆   ┆           ┆           ┆ SINOVAC/B ┆          │
│ -ba02-056 ┆ d157c77cd ┆           ┆           ┆   ┆           ┆           ┆ UTANTAN - ┆          │
│ 77e…      ┆ f27…      ┆           ┆           ┆   ┆           ┆           ┆ CO…       ┆          │
│ 3eec8083- ┆ 2dab386a5 ┆ 64        ┆ 1957-04-0 ┆ … ┆ 2ª Dose   ┆ 85        ┆ COVID-19  ┆ Novo PNI │
│ f305-4750 ┆ f89ea0f64 ┆           ┆ 7         ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│ -904d-6b2 ┆ 31405e0fd ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│ 785…      ┆ 507…      ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

shape: (351_264, 32)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ document_ ┆ paciente_ ┆ paciente_ ┆ paciente_ ┆ … ┆ vacina_de ┆ vacina_co ┆ vacina_no ┆ sistema_ │
│ id        ┆ id        ┆ idade     ┆ dataNasci ┆   ┆ scricao_d ┆ digo      ┆ me        ┆ origem   │
│ ---       ┆ ---       ┆ ---       ┆ mento     ┆   ┆ ose       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ i64       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ str      │
│           ┆           ┆           ┆ date      ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 485d7c3e- ┆ 8863c1423 ┆ 1         ┆ 2022-09-0 ┆ … ┆ Única     ┆ 33        ┆ INF3      ┆ Novo PNI │
│ ae77-4f2b ┆ 83a7fdf28 ┆           ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│ -9d49-f4c ┆ 847ae8187 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 897…      ┆ c36…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ b29481b6- ┆ 200a51a7a ┆ 40        ┆ 1981-07-2 ┆ … ┆ 2ª Dose   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│ 8f40-465f ┆ e9ad13bfb ┆           ┆ 6         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -bb6d-723 ┆ 0ffcb26df ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ d63…      ┆ 858…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 486a03d9- ┆ 967654cd9 ┆ 1         ┆ 2022-05-2 ┆ … ┆ 2ª Dose   ┆ 102       ┆ COVID-19  ┆ Novo PNI │
│ e333-424b ┆ 8da34327f ┆           ┆ 9         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -b5d1-f69 ┆ cadd37a88 ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 395…      ┆ aad…      ┆           ┆           ┆   ┆           ┆           ┆ PE…       ┆          │
│ acabdab4- ┆ 22282860c ┆ 41        ┆ 1982-12-0 ┆ … ┆ Única     ┆ 33        ┆ INF3      ┆ Novo PNI │
│ 73d6-43c7 ┆ 138ceda2c ┆           ┆ 2         ┆   ┆           ┆           ┆           ┆          │
│ -b514-117 ┆ 04266afe5 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 053…      ┆ eba…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 48d451ac- ┆ ae0eb283f ┆ 25        ┆ 1996-11-0 ┆ … ┆ Reforço   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│ c089-4c24 ┆ 5261e384c ┆           ┆ 4         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -b381-856 ┆ 682ed616c ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ a64…      ┆ 0a8…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 47a81519- ┆ 32ff0caa6 ┆ 53        ┆ 1968-02-1 ┆ … ┆ Dose      ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│ d0e9-4688 ┆ c21bf081b ┆           ┆ 7         ┆   ┆ Adicional ┆           ┆ PFIZER -  ┆          │
│ -aa78-c51 ┆ 78261e8ab ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ d17…      ┆ c1c…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 47ce7f1d- ┆ 4fd9ea678 ┆ 53        ┆ 1968-06-0 ┆ … ┆ 1ª Dose   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│ 10e7-4e0d ┆ a53395cfa ┆           ┆ 7         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -8552-2a0 ┆ ad7b453a0 ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ fd4…      ┆ 842…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 47d9bbc1- ┆ c8a1ea6bc ┆ 55        ┆ 1966-11-2 ┆ … ┆ Reforço   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│ 9265-4254 ┆ 4df5a22bf ┆           ┆ 2         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -94bc-752 ┆ 07f9a6a2c ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 3ed…      ┆ 03c…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 47dbed9d- ┆ d0268e0b2 ┆ 8         ┆ 2014-01-2 ┆ … ┆ 1ª Dose   ┆ 99        ┆ COVID-19  ┆ Novo PNI │
│ 7952-4f0f ┆ 550125091 ┆           ┆ 9         ┆   ┆           ┆           ┆ PEDIÁTRIC ┆          │
│ -9d9a-9d5 ┆ 04b27f964 ┆           ┆           ┆   ┆           ┆           ┆ A -       ┆          │
│ 349…      ┆ f5e…      ┆           ┆           ┆   ┆           ┆           ┆ PFIZER C… ┆          │
│ 47dcefd9- ┆ e92fd23a6 ┆ 54        ┆ 1967-06-1 ┆ … ┆ 2ª Dose   ┆ 85        ┆ COVID-19  ┆ Novo PNI │
│ 1478-4eea ┆ 5be9a8f6e ┆           ┆ 7         ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│ -8b7b-a7e ┆ 0dc5862b0 ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│ b23…      ┆ 8fd…      ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [4]:
# Selecionar apenas colunas importantes
q_simples = inicial.select([
    "paciente_endereco_uf",
    "paciente_endereco_nmMunicipio",
    "paciente_idade",
    "vacina_nome",
    "vacina_dataAplicacao"
])

# Remover colunas menos úteis/pesadas
q_sem_codigos = inicial.drop([
    "document_id",
    "paciente_id"
])

# Seleciona tudo EXCETO as colunas listadas
q_sem_codigos = inicial.select(
    pl.exclude([
        "document_id",
        "paciente_id"
    ])
)

display(q_simples.collect())
display(q_sem_codigos.collect())

shape: (384_332, 5)
┌────────────────────┬────────────────────┬────────────────┬───────────────────┬───────────────────┐
│ paciente_endereco_ ┆ paciente_endereco_ ┆ paciente_idade ┆ vacina_nome       ┆ vacina_dataAplica │
│ uf                 ┆ nmMunicipio        ┆ ---            ┆ ---               ┆ cao               │
│ ---                ┆ ---                ┆ i64            ┆ str               ┆ ---               │
│ str                ┆ str                ┆                ┆                   ┆ date              │
╞════════════════════╪════════════════════╪════════════════╪═══════════════════╪═══════════════════╡
│ AP                 ┆ PEDRA BRANCA DO    ┆ 1              ┆ INF3              ┆ 2024-01-24        │
│                    ┆ AMAPARI            ┆                ┆                   ┆                   │
│ AP                 ┆ VITORIA DO JARI    ┆ 40             ┆ COVID-19 PFIZER - ┆ 2021-09-21        │
│                    ┆                    ┆                ┆ COMIRNATY         ┆                   │
│ AP                 ┆ MACAPA             ┆ 1              ┆ COVID-19 PFIZER - ┆ 2024-02-29        │
│                    ┆                    ┆                ┆ COMIRNATY PE…     ┆                   │
│ AP                 ┆ AMAPA              ┆ 41             ┆ INF3              ┆ 2024-01-29        │
│ AP                 ┆ MACAPA             ┆ 25             ┆ COVID-19 PFIZER - ┆ 2022-01-14        │
│                    ┆                    ┆                ┆ COMIRNATY         ┆                   │
│ …                  ┆ …                  ┆ …              ┆ …                 ┆ …                 │
│ AP                 ┆ MACAPA             ┆ 53             ┆ COVID-19 PFIZER - ┆ 2021-11-10        │
│                    ┆                    ┆                ┆ COMIRNATY         ┆                   │
│ AP                 ┆ MACAPA             ┆ 53             ┆ COVID-19 PFIZER - ┆ 2021-06-22        │
│                    ┆                    ┆                ┆ COMIRNATY         ┆                   │
│ AP                 ┆ SANTANA            ┆ 55             ┆ COVID-19 PFIZER - ┆ 2022-01-27        │
│                    ┆                    ┆                ┆ COMIRNATY         ┆                   │
│ AP                 ┆ OIAPOQUE           ┆ 8              ┆ COVID-19          ┆ 2022-07-12        │
│                    ┆                    ┆                ┆ PEDIÁTRICA -      ┆                   │
│                    ┆                    ┆                ┆ PFIZER C…         ┆                   │
│ AP                 ┆ MACAPA             ┆ 54             ┆ COVID-19 ASTRAZEN ┆ 2021-08-09        │
│                    ┆                    ┆                ┆ ECA/FIOCRUZ -…    ┆                   │
└────────────────────┴────────────────────┴────────────────┴───────────────────┴───────────────────┘

shape: (384_332, 30)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ paciente_ ┆ paciente_ ┆ paciente_ ┆ paciente_ ┆ … ┆ vacina_de ┆ vacina_co ┆ vacina_no ┆ sistema_ │
│ idade     ┆ dataNasci ┆ enumSexoB ┆ racaCor_c ┆   ┆ scricao_d ┆ digo      ┆ me        ┆ origem   │
│ ---       ┆ mento     ┆ iologico  ┆ odigo     ┆   ┆ ose       ┆ ---       ┆ ---       ┆ ---      │
│ i64       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ str      │
│           ┆ date      ┆ str       ┆ str       ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1         ┆ 2022-09-0 ┆ F         ┆ 03        ┆ … ┆ Única     ┆ 33        ┆ INF3      ┆ Novo PNI │
│           ┆ 5         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 40        ┆ 1981-07-2 ┆ M         ┆ 03        ┆ … ┆ 2ª Dose   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│           ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 1         ┆ 2022-05-2 ┆ M         ┆ 03        ┆ … ┆ 2ª Dose   ┆ 102       ┆ COVID-19  ┆ Novo PNI │
│           ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ PE…       ┆          │
│ 41        ┆ 1982-12-0 ┆ M         ┆ 03        ┆ … ┆ Única     ┆ 33        ┆ INF3      ┆ Novo PNI │
│           ┆ 2         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 25        ┆ 1996-11-0 ┆ F         ┆ 99        ┆ … ┆ Reforço   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│           ┆ 4         ┆           ┆           ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 53        ┆ 1968-02-1 ┆ M         ┆ 99        ┆ … ┆ Dose      ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│           ┆ 7         ┆           ┆           ┆   ┆ Adicional ┆           ┆ PFIZER -  ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 53        ┆ 1968-06-0 ┆ F         ┆ 03        ┆ … ┆ 1ª Dose   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│           ┆ 7         ┆           ┆           ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 55        ┆ 1966-11-2 ┆ M         ┆ 99        ┆ … ┆ Reforço   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│           ┆ 2         ┆           ┆           ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 8         ┆ 2014-01-2 ┆ M         ┆ 03        ┆ … ┆ 1ª Dose   ┆ 99        ┆ COVID-19  ┆ Novo PNI │
│           ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆ PEDIÁTRIC ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ A -       ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ PFIZER C… ┆          │
│ 54        ┆ 1967-06-1 ┆ F         ┆ 03        ┆ … ┆ 2ª Dose   ┆ 85        ┆ COVID-19  ┆ Novo PNI │
│           ┆ 7         ┆           ┆           ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
# Categorizar faixa etária
q_categoria = inicial.with_columns(
    pl.when(pl.col("paciente_idade") >= 60)
    .then(pl.lit("Idoso"))
    .when(pl.col("paciente_idade") >= 18)
    .then(pl.lit("Adulto"))
    .otherwise(pl.lit("Menor de Idade"))
    .alias("FAIXA_ETARIA")
)

display(
    q_categoria.select([
        "paciente_idade",
        "FAIXA_ETARIA"
    ]).collect()
)

shape: (384_332, 2)
┌────────────────┬────────────────┐
│ paciente_idade ┆ FAIXA_ETARIA   │
│ ---            ┆ ---            │
│ i64            ┆ str            │
╞════════════════╪════════════════╡
│ 1              ┆ Menor de Idade │
│ 40             ┆ Adulto         │
│ 1              ┆ Menor de Idade │
│ 41             ┆ Adulto         │
│ 25             ┆ Adulto         │
│ …              ┆ …              │
│ 53             ┆ Adulto         │
│ 53             ┆ Adulto         │
│ 55             ┆ Adulto         │
│ 8              ┆ Menor de Idade │
│ 54             ┆ Adulto         │
└────────────────┴────────────────┘

In [8]:
# Análise por faixa etária
q_analise_categoria = (
    q_categoria
    .group_by("FAIXA_ETARIA")
    .agg([
        pl.len().alias("total_pessoas"),
        pl.col("paciente_idade").mean().alias("media_idade"),
        pl.col("paciente_idade").min().alias("menor_idade"),
        pl.col("paciente_idade").max().alias("maior_idade")
    ])
    .sort("media_idade", descending=True)
)

display(q_analise_categoria.collect())

shape: (3, 5)
┌────────────────┬───────────────┬─────────────┬─────────────┬─────────────┐
│ FAIXA_ETARIA   ┆ total_pessoas ┆ media_idade ┆ menor_idade ┆ maior_idade │
│ ---            ┆ ---           ┆ ---         ┆ ---         ┆ ---         │
│ str            ┆ u32           ┆ f64         ┆ i64         ┆ i64         │
╞════════════════╪═══════════════╪═════════════╪═════════════╪═════════════╡
│ Idoso          ┆ 51275         ┆ 69.351263   ┆ 60          ┆ 120         │
│ Adulto         ┆ 240992        ┆ 36.382087   ┆ 18          ┆ 59          │
│ Menor de Idade ┆ 92065         ┆ 9.234663    ┆ 0           ┆ 17          │
└────────────────┴───────────────┴─────────────┴─────────────┴─────────────┘

In [9]:
# Pegar as primeiras 10 linhas
q_head = inicial.head(10)

# Pegar da linha 100 até a 150
q_meio = inicial.slice(100, 50)

display(q_head.collect())
display(q_meio.collect())

shape: (10, 32)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ document_ ┆ paciente_ ┆ paciente_ ┆ paciente_ ┆ … ┆ vacina_de ┆ vacina_co ┆ vacina_no ┆ sistema_ │
│ id        ┆ id        ┆ idade     ┆ dataNasci ┆   ┆ scricao_d ┆ digo      ┆ me        ┆ origem   │
│ ---       ┆ ---       ┆ ---       ┆ mento     ┆   ┆ ose       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ i64       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ str      │
│           ┆           ┆           ┆ date      ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 485d7c3e- ┆ 8863c1423 ┆ 1         ┆ 2022-09-0 ┆ … ┆ Única     ┆ 33        ┆ INF3      ┆ Novo PNI │
│ ae77-4f2b ┆ 83a7fdf28 ┆           ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│ -9d49-f4c ┆ 847ae8187 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 897…      ┆ c36…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ b29481b6- ┆ 200a51a7a ┆ 40        ┆ 1981-07-2 ┆ … ┆ 2ª Dose   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│ 8f40-465f ┆ e9ad13bfb ┆           ┆ 6         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -bb6d-723 ┆ 0ffcb26df ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ d63…      ┆ 858…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 486a03d9- ┆ 967654cd9 ┆ 1         ┆ 2022-05-2 ┆ … ┆ 2ª Dose   ┆ 102       ┆ COVID-19  ┆ Novo PNI │
│ e333-424b ┆ 8da34327f ┆           ┆ 9         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -b5d1-f69 ┆ cadd37a88 ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 395…      ┆ aad…      ┆           ┆           ┆   ┆           ┆           ┆ PE…       ┆          │
│ acabdab4- ┆ 22282860c ┆ 41        ┆ 1982-12-0 ┆ … ┆ Única     ┆ 33        ┆ INF3      ┆ Novo PNI │
│ 73d6-43c7 ┆ 138ceda2c ┆           ┆ 2         ┆   ┆           ┆           ┆           ┆          │
│ -b514-117 ┆ 04266afe5 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 053…      ┆ eba…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 48d451ac- ┆ ae0eb283f ┆ 25        ┆ 1996-11-0 ┆ … ┆ Reforço   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│ c089-4c24 ┆ 5261e384c ┆           ┆ 4         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -b381-856 ┆ 682ed616c ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ a64…      ┆ 0a8…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ c6286837- ┆ 30dab7549 ┆ 33        ┆ 1988-10-1 ┆ … ┆ 2ª Dose   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│ 11b8-4b1c ┆ bba8eafab ┆           ┆ 3         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -b617-deb ┆ 72e88b4e2 ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 3c9…      ┆ 1da…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 48d4c016- ┆ f07994351 ┆ 35        ┆ 1987-04-0 ┆ … ┆ Reforço   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│ 28fb-4a99 ┆ 1d71531c3 ┆           ┆ 3         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -8ae4-295 ┆ f10340e6b ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 9f5…      ┆ 013…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ e2d81b38- ┆ 58c052f9d ┆ 54        ┆ 1966-05-1 ┆ … ┆ 1ª Dose   ┆ 85        ┆ COVID-19  ┆ Novo PNI │
│ b477-4beb ┆ 7eedd9d2a ┆           ┆ 5         ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│ -b4eb-722 ┆ 7bbb78467 ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│ 304…      ┆ 0a2…      ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
│ 48e3a459- ┆ bbc4266ac ┆ 22        ┆ 1999-08-0 ┆ … ┆ 2ª Dose   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│ 556f-45dd ┆ 129f6faea ┆           ┆ 9         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -a74a-2bd ┆ 8a0e5d40d ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ a2e…      ┆ d2d…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 038cde87- ┆ cdae6c62a ┆ 59        ┆ 1963-05-2 ┆ … ┆ Reforço   ┆ 103       ┆ COVID-19  ┆ Novo PNI │
│ 1f1a-4b8b ┆ cc6f73074 ┆           ┆ 1         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -bf48-625 ┆ f533dc41b ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 939…      ┆ a07…      ┆           ┆           ┆   ┆           ┆           ┆ BI…       ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

shape: (50, 32)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ document_ ┆ paciente_ ┆ paciente_ ┆ paciente_ ┆ … ┆ vacina_de ┆ vacina_co ┆ vacina_no ┆ sistema_ │
│ id        ┆ id        ┆ idade     ┆ dataNasci ┆   ┆ scricao_d ┆ digo      ┆ me        ┆ origem   │
│ ---       ┆ ---       ┆ ---       ┆ mento     ┆   ┆ ose       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ i64       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ str      │
│           ┆           ┆           ┆ date      ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 4f0c4193- ┆ 4b1fde5d7 ┆ 27        ┆ 1996-05-0 ┆ … ┆ 2ª Dose   ┆ 103       ┆ COVID-19  ┆ Novo PNI │
│ b5a9-4cf4 ┆ cab49a88a ┆           ┆ 9         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -b8b3-471 ┆ b8525cfd6 ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 13e…      ┆ 2f3…      ┆           ┆           ┆   ┆           ┆           ┆ BI…       ┆          │
│ 9773109b- ┆ 25e17e15f ┆ 26        ┆ 1994-12-1 ┆ … ┆ 1ª Dose   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│ b7a9-4b66 ┆ aa5d1f71e ┆           ┆ 8         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -95a2-aa3 ┆ 9068a54e7 ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 071…      ┆ 061…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4f2a24fc- ┆ 15f757f40 ┆ 72        ┆ 1948-05-2 ┆ … ┆ 2ª Dose   ┆ 86        ┆ COVID-19  ┆ Novo PNI │
│ fa9b-47e1 ┆ 5091db3bc ┆           ┆ 4         ┆   ┆           ┆           ┆ SINOVAC/B ┆          │
│ -805f-228 ┆ fee3d88dd ┆           ┆           ┆   ┆           ┆           ┆ UTANTAN - ┆          │
│ f68…      ┆ 00c…      ┆           ┆           ┆   ┆           ┆           ┆ CO…       ┆          │
│ 1b6dd04e- ┆ 05750b38d ┆ 63        ┆ 1958-04-0 ┆ … ┆ 1ª Dose   ┆ 85        ┆ COVID-19  ┆ Novo PNI │
│ 385e-4286 ┆ 97f21c77b ┆           ┆ 3         ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│ -ba73-a57 ┆ 2ed3ed39e ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│ b93…      ┆ c18…      ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
│ 4f32869b- ┆ 822f1b461 ┆ 19        ┆ 2003-02-0 ┆ … ┆ 2ª Dose   ┆ 87        ┆ COVID-19  ┆ Novo PNI │
│ 5bdf-4057 ┆ bb40e3ca1 ┆           ┆ 3         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -bb1b-cd2 ┆ 84fbf89ae ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ b09…      ┆ 817…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 0c6bdfc5- ┆ 1dedbf417 ┆ 71        ┆ 1952-04-1 ┆ … ┆ Única     ┆ 33        ┆ INF3      ┆ Novo PNI │
│ 0a2f-4bb4 ┆ e49d2d808 ┆           ┆ 7         ┆   ┆           ┆           ┆           ┆          │
│ -87f0-887 ┆ aaa3c7e62 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 19b…      ┆ 5cb…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 5251dc20- ┆ ba81ee491 ┆ 3         ┆ 2020-07-0 ┆ … ┆ Única     ┆ 33        ┆ INF3      ┆ Novo PNI │
│ 517b-47ed ┆ 2ca4f5eaa ┆           ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│ -8f60-bfc ┆ a747fb9fd ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ e0a…      ┆ b84…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 183171d7- ┆ 556b076b3 ┆ 26        ┆ 1994-12-2 ┆ … ┆ 2ª Dose   ┆ 86        ┆ COVID-19  ┆ Novo PNI │
│ a27e-4aab ┆ c06668af6 ┆           ┆ 9         ┆   ┆           ┆           ┆ SINOVAC/B ┆          │
│ -8658-274 ┆ 2e11e43eb ┆           ┆           ┆   ┆           ┆           ┆ UTANTAN - ┆          │
│ eda…      ┆ 15b…      ┆           ┆           ┆   ┆           ┆           ┆ CO…       ┆          │
│ 525c9c70- ┆ f2f2f0c80 ┆ 69        ┆ 1951-10-1 ┆ … ┆ 1ª Dose   ┆ 86        ┆ COVID-19  ┆ Novo PNI │
│ fa01-465c ┆ 7a86ef9d5 ┆           ┆ 7         ┆   ┆           ┆           ┆ SINOVAC/B ┆          │
│ -8652-58e ┆ 8cbf4b043 ┆           ┆           ┆   ┆           ┆           ┆ UTANTAN - ┆          │
│ 269…      ┆ 552…      ┆           ┆           ┆   ┆           ┆           ┆ CO…       ┆          │
│ 787606c7- ┆ c49f14203 ┆ 54        ┆ 1968-02-1 ┆ … ┆ Reforço   ┆ 85        ┆ COVID-19  ┆ Novo PNI │
│ 201c-4af9 ┆ 9a164e8cb ┆           ┆ 6         ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│ -bf0d-74d ┆ 8d00665d4 ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│ 9b1…      ┆ 240…      ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [10]:
# Recorte de linhas específicas
q_recorte_indices = (
    inicial
    .with_row_index("id_linha")
    .filter(pl.col("id_linha").is_in([0, 10, 50]))
    .select([
        "paciente_endereco_uf",
        "paciente_endereco_nmMunicipio"
    ])
)

display(q_recorte_indices.collect())

shape: (3, 2)
┌──────────────────────┬───────────────────────────────┐
│ paciente_endereco_uf ┆ paciente_endereco_nmMunicipio │
│ ---                  ┆ ---                           │
│ str                  ┆ str                           │
╞══════════════════════╪═══════════════════════════════╡
│ AP                   ┆ PEDRA BRANCA DO AMAPARI       │
│ AP                   ┆ CUTIAS                        │
│ PA                   ┆ PORTEL                        │
└──────────────────────┴───────────────────────────────┘

In [11]:
q_stats_mun = (
    inicial.group_by("paciente_endereco_nmMunicipio")
    .agg([
        pl.len().alias("total_vacinados"),
        pl.col("paciente_idade").mean().alias("media_idade"),
        pl.col("paciente_idade").max().alias("maior_idade"),
        pl.col("paciente_endereco_uf").first().alias("uf_origem")
    ])
    .sort("total_vacinados", descending=True)
)

display(q_stats_mun.collect())

shape: (1_619, 5)
┌───────────────────────────────┬─────────────────┬─────────────┬─────────────┬───────────┐
│ paciente_endereco_nmMunicipio ┆ total_vacinados ┆ media_idade ┆ maior_idade ┆ uf_origem │
│ ---                           ┆ ---             ┆ ---         ┆ ---         ┆ ---       │
│ str                           ┆ u32             ┆ f64         ┆ i64         ┆ str       │
╞═══════════════════════════════╪═════════════════╪═════════════╪═════════════╪═══════════╡
│ MACAPA                        ┆ 214598          ┆ 35.473793   ┆ 120         ┆ AP        │
│ SANTANA                       ┆ 51094           ┆ 34.359749   ┆ 113         ┆ AP        │
│ LARANJAL DO JARI              ┆ 17629           ┆ 31.964661   ┆ 104         ┆ AP        │
│ MAZAGAO                       ┆ 10689           ┆ 27.283469   ┆ 100         ┆ AP        │
│ OIAPOQUE                      ┆ 8459            ┆ 30.767703   ┆ 103         ┆ AP        │
│ …                             ┆ …               ┆ …           ┆ …           ┆ …         │
│ CANINDE                       ┆ 1               ┆ 35.0        ┆ 35          ┆ CE        │
│ FRANCISCO MACEDO              ┆ 1               ┆ 18.0        ┆ 18          ┆ PI        │
│ FATIMA                        ┆ 1               ┆ 32.0        ┆ 32          ┆ BA        │
│ JAGUARE                       ┆ 1               ┆ 32.0        ┆ 32          ┆ ES        │
│ ICATU                         ┆ 1               ┆ 59.0        ┆ 59          ┆ MA        │
└───────────────────────────────┴─────────────────┴─────────────┴─────────────┴───────────┘

In [12]:
import polars as pl
import time

print("=== TESTE 1: Processamento SEM StringCache ===")
start_1 = time.time()

q_sem_cache = (
    pl.scan_parquet(r"C:\Users\Usuario\OneDrive\Documentos\Covid_AC.parquet")
    .with_columns(
        pl.col("paciente_idade").cast(pl.Int64, strict=False),
        pl.col("paciente_dataNascimento").str.to_date("%Y-%m-%d", strict=False),
        pl.col("vacina_dataAplicacao").str.to_date("%Y-%m-%d", strict=False)
    )
    .group_by(["paciente_endereco_uf", "paciente_endereco_nmMunicipio"])
    .agg([
        pl.col("paciente_idade").mean().alias("media_idade"),
        pl.col("paciente_idade").std().alias("desvio_idade")
    ])
    .sort("media_idade", descending=True)
)

df_1 = q_sem_cache.collect()
end_1 = time.time()
tempo_sem = end_1 - start_1

print(f"Tempo SEM Cache: {tempo_sem:.4f} segundos")
print(f"Uso de memória estimado (coluna UF): {df_1['paciente_endereco_uf'].estimated_size()} bytes\n")

display(df_1)

=== TESTE 1: Processamento SEM StringCache ===
Tempo SEM Cache: 0.0495 segundos
Uso de memória estimado (coluna UF): 3120 bytes

shape: (1_563, 4)
┌──────────────────────┬───────────────────────────────┬─────────────┬──────────────┐
│ paciente_endereco_uf ┆ paciente_endereco_nmMunicipio ┆ media_idade ┆ desvio_idade │
│ ---                  ┆ ---                           ┆ ---         ┆ ---          │
│ str                  ┆ str                           ┆ f64         ┆ f64          │
╞══════════════════════╪═══════════════════════════════╪═════════════╪══════════════╡
│ RR                   ┆ CANTA                         ┆ 104.0       ┆ 1.414214     │
│ RS                   ┆ PORTAO                        ┆ 94.0        ┆ null         │
│ RS                   ┆ PLANALTO                      ┆ 92.0        ┆ 1.414214     │
│ MG                   ┆ BOCAINA DE MINAS              ┆ 89.0        ┆ null         │
│ BA                   ┆ TAPEROA                       ┆ 89.0        ┆ null         │
│ …                    ┆ …                             ┆ …           ┆ …            │
│ CE                   ┆ IGUATU                        ┆ 4.0         ┆ 1.414214     │
│ SC                   ┆ CAPIVARI DE BAIXO             ┆ 4.0         ┆ null         │
│ BA                   ┆ AMARGOSA                      ┆ 3.0         ┆ null         │
│ CE                   ┆ ARACOIABA                     ┆ 2.0         ┆ null         │
│ MG                   ┆ IGARAPE                       ┆ 0.0         ┆ null         │
└──────────────────────┴───────────────────────────────┴─────────────┴──────────────┘

In [13]:
print("=== TESTE 2: Processamento COM StringCache ===")

with pl.StringCache():
    start_2 = time.time()

    q_com_cache = (
        pl.scan_parquet(r"C:\Users\Usuario\OneDrive\Documentos\Covid_AC.parquet")
        .with_columns(
            pl.col("paciente_idade").cast(pl.Int64, strict=False),
            pl.col("paciente_dataNascimento").str.to_date("%Y-%m-%d", strict=False),
            pl.col("vacina_dataAplicacao").str.to_date("%Y-%m-%d", strict=False)
        )
        .group_by([
            "paciente_endereco_uf",
            "paciente_endereco_nmMunicipio"
        ])
        .agg([
            pl.col("paciente_idade").mean().alias("media_idade"),
            pl.col("paciente_idade").std().alias("desvio_idade")
        ])
        .sort("media_idade", descending=True)
    )

    df_2 = q_com_cache.collect()
    end_2 = time.time()

tempo_com = end_2 - start_2

print(f"Tempo COM Cache: {tempo_com:.4f} segundos")
print(f"Uso de memória estimado (coluna UF): {df_2['paciente_endereco_uf'].estimated_size()} bytes\n")

=== TESTE 2: Processamento COM StringCache ===
Tempo COM Cache: 0.0329 segundos
Uso de memória estimado (coluna UF): 3120 bytes