In [1]:
import polars as pl
import time

In [2]:
import polars as pl

inicial = (
    pl.scan_parquet(r"C:\Users\diogo.durao\Documents\covid_sp.parquet")
    .with_columns(
        pl.col("paciente_idade").cast(pl.Int64, strict=False),
        pl.col("paciente_dataNascimento").str.to_date("%Y-%m-%d", strict=False),
        pl.col("vacina_dataAplicacao").str.to_date("%Y-%m-%d", strict=False)
    )
)

display(inicial.collect().head())

shape: (5, 32)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ document_ ┆ paciente_ ┆ paciente_ ┆ paciente_ ┆ … ┆ vacina_de ┆ vacina_co ┆ vacina_no ┆ sistema_ │
│ id        ┆ id        ┆ idade     ┆ dataNasci ┆   ┆ scricao_d ┆ digo      ┆ me        ┆ origem   │
│ ---       ┆ ---       ┆ ---       ┆ mento     ┆   ┆ ose       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ i64       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ str      │
│           ┆           ┆           ┆ date      ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ a235dbb4- ┆ 5d574f13b ┆ 32        ┆ 1989-05-2 ┆ … ┆ Reforço   ┆ 88        ┆ COVID-19  ┆ VACIVIDA │
│ 3391-419f ┆ 6065a3aa6 ┆           ┆ 9         ┆   ┆           ┆           ┆ JANSSEN - ┆          │
│ -bdf9-cfe ┆ 16b5b4757 ┆           ┆           ┆   ┆           ┆           ┆ Ad26.COV2 ┆          │
│ d14…      ┆ 50e…      ┆           ┆           ┆   ┆           ┆           ┆ .S        ┆          │
│ 90c1176e- ┆ 9fb17b039 ┆ 59        ┆ 1961-09-0 ┆ … ┆ 1ª Dose   ┆ 85        ┆ COVID-19  ┆ VACIVIDA │
│ 561b-4af4 ┆ bb026f66e ┆           ┆ 6         ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│ -8751-cea ┆ f1c21af1d ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│ ead…      ┆ ace…      ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
│ a2368077- ┆ b4462f225 ┆ 85        ┆ 1936-03-0 ┆ … ┆ Reforço   ┆ 87        ┆ COVID-19  ┆ VACIVIDA │
│ 7cfd-4421 ┆ ccdd46e27 ┆           ┆ 9         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -89a2-470 ┆ babc5da0e ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ e02…      ┆ c10…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 90c12c21- ┆ 60e8d202b ┆ 35        ┆ 1985-11-2 ┆ … ┆ 2ª Dose   ┆ 86        ┆ COVID-19  ┆ VACIVIDA │
│ e62b-4bbf ┆ 7d1874fe1 ┆           ┆ 2         ┆   ┆           ┆           ┆ SINOVAC/B ┆          │
│ -8e0b-a28 ┆ b92eaa665 ┆           ┆           ┆   ┆           ┆           ┆ UTANTAN - ┆          │
│ be8…      ┆ ed0…      ┆           ┆           ┆   ┆           ┆           ┆ CO…       ┆          │
│ a236e352- ┆ a143b41e6 ┆ 53        ┆ 1968-05-1 ┆ … ┆ 2ª Dose   ┆ 87        ┆ COVID-19  ┆ VACIVIDA │
│ a927-47bb ┆ 1d2f48d9c ┆           ┆ 8         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -970c-e43 ┆ cbdb456ec ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 2d0…      ┆ 68f…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [3]:
# Filtro Simples: Apenas pacientes do Acre
q_ac = inicial.filter(
    pl.col("paciente_endereco_uf") == "AC"
)

# Filtro Composto: Acre e idade maior que 60
q_ac_idosos = inicial.filter(
    (pl.col("paciente_endereco_uf") == "AC") &
    (pl.col("paciente_idade") > 60)
)

# Filtro com Lista: Apenas AC e AP
q_estados = inicial.filter(
    pl.col("paciente_endereco_uf").is_in(["AC", "AP"])
)

display(q_ac.collect())
display(q_ac_idosos.collect())
display(q_estados.collect())

shape: (3_452, 32)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ document_ ┆ paciente_ ┆ paciente_ ┆ paciente_ ┆ … ┆ vacina_de ┆ vacina_co ┆ vacina_no ┆ sistema_ │
│ id        ┆ id        ┆ idade     ┆ dataNasci ┆   ┆ scricao_d ┆ digo      ┆ me        ┆ origem   │
│ ---       ┆ ---       ┆ ---       ┆ mento     ┆   ┆ ose       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ i64       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ str      │
│           ┆           ┆           ┆ date      ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ aad8c2f1- ┆ 63644dddb ┆ 11        ┆ 2010-09-0 ┆ … ┆ 2ª Dose   ┆ 99        ┆ COVID-19  ┆ VACIVIDA │
│ ad27-4e49 ┆ 6bba44bb2 ┆           ┆ 5         ┆   ┆           ┆           ┆ PEDIÁTRIC ┆          │
│ -89b1-b9e ┆ 2325f1279 ┆           ┆           ┆   ┆           ┆           ┆ A -       ┆          │
│ e0b…      ┆ e62…      ┆           ┆           ┆   ┆           ┆           ┆ PFIZER C… ┆          │
│ c1e32c68- ┆ d3ce068d0 ┆ 22        ┆ 1999-06-2 ┆ … ┆ 1ª Dose   ┆ 87        ┆ COVID-19  ┆ VACIVIDA │
│ 63b6-438e ┆ 523c36a7b ┆           ┆ 9         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -9503-343 ┆ 126aa460c ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 3e1…      ┆ bbb…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ b232bf8a- ┆ 8f85e1ea1 ┆ 80        ┆ 1940-06-2 ┆ … ┆ 1ª Dose   ┆ 85        ┆ COVID-19  ┆ VACIVIDA │
│ 90ae-40c4 ┆ 665393cfb ┆           ┆ 9         ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│ -853e-6f3 ┆ 7d960caea ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│ 592…      ┆ 1c1…      ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
│ be2a4668- ┆ e32f94b61 ┆ 11        ┆ 2011-02-0 ┆ … ┆ 2ª Dose   ┆ 86        ┆ COVID-19  ┆ VACIVIDA │
│ f876-435b ┆ 752831458 ┆           ┆ 6         ┆   ┆           ┆           ┆ SINOVAC/B ┆          │
│ -a1a0-4e2 ┆ 9377be945 ┆           ┆           ┆   ┆           ┆           ┆ UTANTAN - ┆          │
│ 43f…      ┆ 123…      ┆           ┆           ┆   ┆           ┆           ┆ CO…       ┆          │
│ c1526e74- ┆ f79e7fec2 ┆ 25        ┆ 1996-05-3 ┆ … ┆ Reforço   ┆ 88        ┆ COVID-19  ┆ VACIVIDA │
│ b1ea-4df2 ┆ 1e6119568 ┆           ┆ 0         ┆   ┆           ┆           ┆ JANSSEN - ┆          │
│ -abff-407 ┆ 48c524ef0 ┆           ┆           ┆   ┆           ┆           ┆ Ad26.COV2 ┆          │
│ ca8…      ┆ b93…      ┆           ┆           ┆   ┆           ┆           ┆ .S        ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ a3f82809- ┆ c9e059b62 ┆ 8         ┆ 2013-03-3 ┆ … ┆ 1ª Dose   ┆ 86        ┆ COVID-19  ┆ VACIVIDA │
│ ff6b-4741 ┆ a612bbe34 ┆           ┆ 0         ┆   ┆           ┆           ┆ SINOVAC/B ┆          │
│ -b671-679 ┆ 0f07a2d0a ┆           ┆           ┆   ┆           ┆           ┆ UTANTAN - ┆          │
│ 581…      ┆ cac…      ┆           ┆           ┆   ┆           ┆           ┆ CO…       ┆          │
│ a82f697f- ┆ 0ff972cd3 ┆ 20        ┆ 2001-07-0 ┆ … ┆ 2ª Dose   ┆ 85        ┆ COVID-19  ┆ VACIVIDA │
│ a562-4161 ┆ 044ff31a2 ┆           ┆ 5         ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│ -9f34-ad7 ┆ ea13aa30f ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│ 455…      ┆ 266…      ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
│ b5a03b86- ┆ 0400637aa ┆ 49        ┆ 1972-09-0 ┆ … ┆ Reforço   ┆ 85        ┆ COVID-19  ┆ VACIVIDA │
│ fcff-4f55 ┆ 3e9e0e57e ┆           ┆ 7         ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│ -b813-2ad ┆ b9ae123e5 ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│ a3f…      ┆ 5d1…      ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
│ b5da4ab3- ┆ 78d671b70 ┆ 17        ┆ 2004-01-2 ┆ … ┆ 2ª Dose   ┆ 87        ┆ COVID-19  ┆ VACIVIDA │
│ 4442-40dc ┆ cf4ccef3b ┆           ┆ 8         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -9be5-38f ┆ 408bfe8cb ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ be3…      ┆ 33b…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ c18c5fb3- ┆ 557860e30 ┆ 35        ┆ 1986-01-0 ┆ … ┆ 1ª Dose   ┆ 86        ┆ COVID-19  ┆ VACIVIDA │
│ 305e-4ed2 ┆ 1cf5f5305 ┆           ┆ 1         ┆   ┆           ┆           ┆ SINOVAC/B ┆          │
│ -b5dd-b2a ┆ 0cdefa4f6 ┆           ┆           ┆   ┆           ┆           ┆ UTANTAN - ┆          │
│ def…      ┆ c8e…      ┆           ┆           ┆   ┆           ┆           ┆ CO…       ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

shape: (361, 32)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ document_ ┆ paciente_ ┆ paciente_ ┆ paciente_ ┆ … ┆ vacina_de ┆ vacina_co ┆ vacina_no ┆ sistema_ │
│ id        ┆ id        ┆ idade     ┆ dataNasci ┆   ┆ scricao_d ┆ digo      ┆ me        ┆ origem   │
│ ---       ┆ ---       ┆ ---       ┆ mento     ┆   ┆ ose       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ i64       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ str      │
│           ┆           ┆           ┆ date      ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ b232bf8a- ┆ 8f85e1ea1 ┆ 80        ┆ 1940-06-2 ┆ … ┆ 1ª Dose   ┆ 85        ┆ COVID-19  ┆ VACIVIDA │
│ 90ae-40c4 ┆ 665393cfb ┆           ┆ 9         ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│ -853e-6f3 ┆ 7d960caea ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│ 592…      ┆ 1c1…      ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
│ ef8b57b5- ┆ 74e82855f ┆ 63        ┆ 1957-11-2 ┆ … ┆ 2ª Dose   ┆ 85        ┆ COVID-19  ┆ VACIVIDA │
│ f3f1-40be ┆ 07c2c594f ┆           ┆ 3         ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│ -ae86-527 ┆ c7f3d5d73 ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│ bfc…      ┆ 797…      ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
│ 74abb2db- ┆ eb8d2f99f ┆ 64        ┆ 1957-07-0 ┆ … ┆ 2ª Dose   ┆ 85        ┆ COVID-19  ┆ VACIVIDA │
│ a245-4072 ┆ 7a6776df6 ┆           ┆ 7         ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│ -bbe9-4ad ┆ 92cf56de0 ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│ b92…      ┆ e36…      ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
│ 252b1e34- ┆ b3a561b0b ┆ 80        ┆ 1943-12-0 ┆ … ┆ Reforço   ┆ 103       ┆ COVID-19  ┆ VACIVIDA │
│ c4db-4a16 ┆ a7ad4f53d ┆           ┆ 7         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -988f-ee5 ┆ a88218ec5 ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ a4f…      ┆ 2dc…      ┆           ┆           ┆   ┆           ┆           ┆ BI…       ┆          │
│ 37bcda82- ┆ 14861b31a ┆ 67        ┆ 1956-10-2 ┆ … ┆ Reforço   ┆ 103       ┆ COVID-19  ┆ VACIVIDA │
│ 44cf-4619 ┆ c2b177807 ┆           ┆ 8         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -947d-ae3 ┆ 25f926dab ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 958…      ┆ f14…      ┆           ┆           ┆   ┆           ┆           ┆ BI…       ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 9aca914b- ┆ 14861b31a ┆ 64        ┆ 1956-10-2 ┆ … ┆ 1ª Dose   ┆ 85        ┆ COVID-19  ┆ VACIVIDA │
│ 19c1-401c ┆ c2b177807 ┆           ┆ 8         ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│ -94bb-32d ┆ 25f926dab ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│ 290…      ┆ f14…      ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
│ 3e966921- ┆ 6d44fa130 ┆ 64        ┆ 1957-06-1 ┆ … ┆ Reforço   ┆ 87        ┆ COVID-19  ┆ VACIVIDA │
│ 0e0d-4832 ┆ 84e9dafeb ┆           ┆ 2         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -af06-faa ┆ a01bc5c8f ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 61d…      ┆ e8d…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ f7e5bff4- ┆ 4b15daa25 ┆ 70        ┆ 1950-06-0 ┆ … ┆ 1ª Dose   ┆ 86        ┆ COVID-19  ┆ VACIVIDA │
│ dd6c-431b ┆ 182736718 ┆           ┆ 6         ┆   ┆           ┆           ┆ SINOVAC/B ┆          │
│ -8a1c-3eb ┆ 186964bd0 ┆           ┆           ┆   ┆           ┆           ┆ UTANTAN - ┆          │
│ b8f…      ┆ df4…      ┆           ┆           ┆   ┆           ┆           ┆ CO…       ┆          │
│ 164cc6f5- ┆ af71f89b3 ┆ 63        ┆ 1960-01-2 ┆ … ┆ Reforço   ┆ 103       ┆ COVID-19  ┆ VACIVIDA │
│ b156-43a4 ┆ 4a18fd136 ┆           ┆ 5         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -beca-8be ┆ 38dd52608 ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 10f…      ┆ 7f2…      ┆           ┆           ┆   ┆           ┆           ┆ BI…       ┆          │
│ 754b34fa- ┆ 9c9be52f7 ┆ 80        ┆ 1940-06-1 ┆ … ┆ 2ª Dose   ┆ 85        ┆ COVID-19  ┆ VACIVIDA │
│ 7929-45b5 ┆ aaef35788 ┆           ┆ 4         ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│ -a92d-7c2 ┆ b6a143394 ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│ aa6…      ┆ 616…      ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

shape: (5_548, 32)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ document_ ┆ paciente_ ┆ paciente_ ┆ paciente_ ┆ … ┆ vacina_de ┆ vacina_co ┆ vacina_no ┆ sistema_ │
│ id        ┆ id        ┆ idade     ┆ dataNasci ┆   ┆ scricao_d ┆ digo      ┆ me        ┆ origem   │
│ ---       ┆ ---       ┆ ---       ┆ mento     ┆   ┆ ose       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ i64       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ str      │
│           ┆           ┆           ┆ date      ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ a35ddaac- ┆ a1a68a203 ┆ 28        ┆ 1993-03-0 ┆ … ┆ 1ª Dose   ┆ 86        ┆ COVID-19  ┆ VACIVIDA │
│ b33a-4fce ┆ a2f9f8b9f ┆           ┆ 9         ┆   ┆           ┆           ┆ SINOVAC/B ┆          │
│ -a9ea-cbb ┆ 51839cbc7 ┆           ┆           ┆   ┆           ┆           ┆ UTANTAN - ┆          │
│ 2c0…      ┆ e3b…      ┆           ┆           ┆   ┆           ┆           ┆ CO…       ┆          │
│ 9a2ab2bf- ┆ f36fdfe89 ┆ 29        ┆ 1992-09-0 ┆ … ┆ Reforço   ┆ 87        ┆ COVID-19  ┆ VACIVIDA │
│ e2bf-48cf ┆ a79f23058 ┆           ┆ 8         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -9939-ca9 ┆ 1cf06aa3d ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ c7e…      ┆ aab…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ba810712- ┆ 29b8a48f2 ┆ 21        ┆ 2002-10-2 ┆ … ┆ Única     ┆ 33        ┆ INF3      ┆ Novo PNI │
│ 0d99-4852 ┆ c23e1d16a ┆           ┆ 4         ┆   ┆           ┆           ┆           ┆          │
│ -a79c-a8d ┆ e47322f6d ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 6df…      ┆ a26…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ aad8c2f1- ┆ 63644dddb ┆ 11        ┆ 2010-09-0 ┆ … ┆ 2ª Dose   ┆ 99        ┆ COVID-19  ┆ VACIVIDA │
│ ad27-4e49 ┆ 6bba44bb2 ┆           ┆ 5         ┆   ┆           ┆           ┆ PEDIÁTRIC ┆          │
│ -89b1-b9e ┆ 2325f1279 ┆           ┆           ┆   ┆           ┆           ┆ A -       ┆          │
│ e0b…      ┆ e62…      ┆           ┆           ┆   ┆           ┆           ┆ PFIZER C… ┆          │
│ c02edac1- ┆ 46bce5f98 ┆ 32        ┆ 1988-11-1 ┆ … ┆ 1ª Dose   ┆ 85        ┆ COVID-19  ┆ VACIVIDA │
│ 8686-4e03 ┆ 062b1fc39 ┆           ┆ 0         ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│ -a4cb-dd2 ┆ db3995346 ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│ 1d2…      ┆ 6bd…      ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ b1673a6a- ┆ fb6eba556 ┆ 17        ┆ 2004-08-2 ┆ … ┆ Reforço   ┆ 86        ┆ COVID-19  ┆ VACIVIDA │
│ 8e38-41d9 ┆ 74e77b298 ┆           ┆ 7         ┆   ┆           ┆           ┆ SINOVAC/B ┆          │
│ -86a8-582 ┆ 9e5dd0bb3 ┆           ┆           ┆   ┆           ┆           ┆ UTANTAN - ┆          │
│ e0b…      ┆ 762…      ┆           ┆           ┆   ┆           ┆           ┆ CO…       ┆          │
│ b5a03b86- ┆ 0400637aa ┆ 49        ┆ 1972-09-0 ┆ … ┆ Reforço   ┆ 85        ┆ COVID-19  ┆ VACIVIDA │
│ fcff-4f55 ┆ 3e9e0e57e ┆           ┆ 7         ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│ -b813-2ad ┆ b9ae123e5 ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│ a3f…      ┆ 5d1…      ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
│ b5da4ab3- ┆ 78d671b70 ┆ 17        ┆ 2004-01-2 ┆ … ┆ 2ª Dose   ┆ 87        ┆ COVID-19  ┆ VACIVIDA │
│ 4442-40dc ┆ cf4ccef3b ┆           ┆ 8         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -9be5-38f ┆ 408bfe8cb ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ be3…      ┆ 33b…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ bc4f44bb- ┆ 8ee18f7b7 ┆ 34        ┆ 1986-12-2 ┆ … ┆ 2ª Dose   ┆ 86        ┆ COVID-19  ┆ VACIVIDA │
│ 4973-41a8 ┆ 320b9896c ┆           ┆ 4         ┆   ┆           ┆           ┆ SINOVAC/B ┆          │
│ -bfc6-3ff ┆ 3b22b5d8c ┆           ┆           ┆   ┆           ┆           ┆ UTANTAN - ┆          │
│ c15…      ┆ 37f…      ┆           ┆           ┆   ┆           ┆           ┆ CO…       ┆          │
│ c18c5fb3- ┆ 557860e30 ┆ 35        ┆ 1986-01-0 ┆ … ┆ 1ª Dose   ┆ 86        ┆ COVID-19  ┆ VACIVIDA │
│ 305e-4ed2 ┆ 1cf5f5305 ┆           ┆ 1         ┆   ┆           ┆           ┆ SINOVAC/B ┆          │
│ -b5dd-b2a ┆ 0cdefa4f6 ┆           ┆           ┆   ┆           ┆           ┆ UTANTAN - ┆          │
│ def…      ┆ c8e…      ┆           ┆           ┆   ┆           ┆           ┆ CO…       ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [4]:
# Selecionar apenas colunas importantes
q_simples = inicial.select([
    "paciente_endereco_uf",
    "paciente_endereco_nmMunicipio",
    "paciente_idade",
    "vacina_nome",
    "vacina_dataAplicacao"
])

# Remover colunas menos úteis/pesadas
q_sem_codigos = inicial.drop([
    "document_id",
    "paciente_id"
])

# Seleciona tudo EXCETO as colunas listadas
q_sem_codigos = inicial.select(
    pl.exclude([
        "document_id",
        "paciente_id"
    ])
)

display(q_simples.collect())
display(q_sem_codigos.collect())

shape: (30_644_153, 5)
┌────────────────────┬────────────────────┬────────────────┬───────────────────┬───────────────────┐
│ paciente_endereco_ ┆ paciente_endereco_ ┆ paciente_idade ┆ vacina_nome       ┆ vacina_dataAplica │
│ uf                 ┆ nmMunicipio        ┆ ---            ┆ ---               ┆ cao               │
│ ---                ┆ ---                ┆ i64            ┆ str               ┆ ---               │
│ str                ┆ str                ┆                ┆                   ┆ date              │
╞════════════════════╪════════════════════╪════════════════╪═══════════════════╪═══════════════════╡
│ SP                 ┆ GUARULHOS          ┆ 32             ┆ COVID-19 JANSSEN  ┆ 2022-04-05        │
│                    ┆                    ┆                ┆ - Ad26.COV2.S     ┆                   │
│ SP                 ┆ IBITINGA           ┆ 59             ┆ COVID-19 ASTRAZEN ┆ 2021-05-31        │
│                    ┆                    ┆                ┆ ECA/FIOCRUZ -…    ┆                   │
│ SP                 ┆ SAO PAULO          ┆ 85             ┆ COVID-19 PFIZER - ┆ 2021-12-04        │
│                    ┆                    ┆                ┆ COMIRNATY         ┆                   │
│ SP                 ┆ SAO PAULO          ┆ 35             ┆ COVID-19          ┆ 2021-08-14        │
│                    ┆                    ┆                ┆ SINOVAC/BUTANTAN  ┆                   │
│                    ┆                    ┆                ┆ - CO…             ┆                   │
│ SP                 ┆ SAO PAULO          ┆ 53             ┆ COVID-19 PFIZER - ┆ 2021-09-14        │
│                    ┆                    ┆                ┆ COMIRNATY         ┆                   │
│ …                  ┆ …                  ┆ …              ┆ …                 ┆ …                 │
│ SP                 ┆ SAO PAULO          ┆ 22             ┆ COVID-19 PFIZER - ┆ 2022-01-27        │
│                    ┆                    ┆                ┆ COMIRNATY         ┆                   │
│ SP                 ┆ CAMPINAS           ┆ 15             ┆ COVID-19 PFIZER - ┆ 2021-11-05        │
│                    ┆                    ┆                ┆ COMIRNATY         ┆                   │
│ SP                 ┆ SAO PAULO          ┆ 81             ┆ COVID-19 ASTRAZEN ┆ 2021-02-27        │
│                    ┆                    ┆                ┆ ECA/FIOCRUZ -…    ┆                   │
│ SP                 ┆ SAO PAULO          ┆ 33             ┆ COVID-19 ASTRAZEN ┆ 2021-08-20        │
│                    ┆                    ┆                ┆ ECA/FIOCRUZ -…    ┆                   │
│ SP                 ┆ SUMARE             ┆ 28             ┆ COVID-19          ┆ 2022-02-25        │
│                    ┆                    ┆                ┆ SINOVAC/BUTANTAN  ┆                   │
│                    ┆                    ┆                ┆ - CO…             ┆                   │
└────────────────────┴────────────────────┴────────────────┴───────────────────┴───────────────────┘

shape: (30_644_153, 30)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ paciente_ ┆ paciente_ ┆ paciente_ ┆ paciente_ ┆ … ┆ vacina_de ┆ vacina_co ┆ vacina_no ┆ sistema_ │
│ idade     ┆ dataNasci ┆ enumSexoB ┆ racaCor_c ┆   ┆ scricao_d ┆ digo      ┆ me        ┆ origem   │
│ ---       ┆ mento     ┆ iologico  ┆ odigo     ┆   ┆ ose       ┆ ---       ┆ ---       ┆ ---      │
│ i64       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ str      │
│           ┆ date      ┆ str       ┆ str       ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 32        ┆ 1989-05-2 ┆ F         ┆ 99        ┆ … ┆ Reforço   ┆ 88        ┆ COVID-19  ┆ VACIVIDA │
│           ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆ JANSSEN - ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Ad26.COV2 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ .S        ┆          │
│ 59        ┆ 1961-09-0 ┆ F         ┆ 01        ┆ … ┆ 1ª Dose   ┆ 85        ┆ COVID-19  ┆ VACIVIDA │
│           ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
│ 85        ┆ 1936-03-0 ┆ M         ┆ 04        ┆ … ┆ Reforço   ┆ 87        ┆ COVID-19  ┆ VACIVIDA │
│           ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 35        ┆ 1985-11-2 ┆ M         ┆ 04        ┆ … ┆ 2ª Dose   ┆ 86        ┆ COVID-19  ┆ VACIVIDA │
│           ┆ 2         ┆           ┆           ┆   ┆           ┆           ┆ SINOVAC/B ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ UTANTAN - ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ CO…       ┆          │
│ 53        ┆ 1968-05-1 ┆ M         ┆ 99        ┆ … ┆ 2ª Dose   ┆ 87        ┆ COVID-19  ┆ VACIVIDA │
│           ┆ 8         ┆           ┆           ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 22        ┆ 1999-12-0 ┆ M         ┆ 99        ┆ … ┆ 2ª Dose   ┆ 87        ┆ COVID-19  ┆ VACIVIDA │
│           ┆ 4         ┆           ┆           ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 15        ┆ 2006-03-3 ┆ M         ┆ 01        ┆ … ┆ 2ª Dose   ┆ 87        ┆ COVID-19  ┆ VACIVIDA │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 81        ┆ 1939-05-3 ┆ M         ┆ 99        ┆ … ┆ 1ª Dose   ┆ 85        ┆ COVID-19  ┆ VACIVIDA │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
│ 33        ┆ 1988-01-2 ┆ F         ┆ 99        ┆ … ┆ 2ª Dose   ┆ 85        ┆ COVID-19  ┆ VACIVIDA │
│           ┆ 3         ┆           ┆           ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
│ 28        ┆ 1993-03-1 ┆ M         ┆ 04        ┆ … ┆ 2ª Dose   ┆ 86        ┆ COVID-19  ┆ VACIVIDA │
│           ┆ 7         ┆           ┆           ┆   ┆           ┆           ┆ SINOVAC/B ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ UTANTAN - ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ CO…       ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
# Categorizar faixa etária
q_categoria = inicial.with_columns(
    pl.when(pl.col("paciente_idade") >= 60)
    .then(pl.lit("Idoso"))
    .when(pl.col("paciente_idade") >= 18)
    .then(pl.lit("Adulto"))
    .otherwise(pl.lit("Menor de Idade"))
    .alias("FAIXA_ETARIA")
)

display(
    q_categoria.select([
        "paciente_idade",
        "FAIXA_ETARIA"
    ]).collect()
)

shape: (30_644_153, 2)
┌────────────────┬────────────────┐
│ paciente_idade ┆ FAIXA_ETARIA   │
│ ---            ┆ ---            │
│ i64            ┆ str            │
╞════════════════╪════════════════╡
│ 32             ┆ Adulto         │
│ 59             ┆ Adulto         │
│ 85             ┆ Idoso          │
│ 35             ┆ Adulto         │
│ 53             ┆ Adulto         │
│ …              ┆ …              │
│ 22             ┆ Adulto         │
│ 15             ┆ Menor de Idade │
│ 81             ┆ Idoso          │
│ 33             ┆ Adulto         │
│ 28             ┆ Adulto         │
└────────────────┴────────────────┘

In [6]:
# Análise por faixa etária
q_analise_categoria = (
    q_categoria
    .group_by("FAIXA_ETARIA")
    .agg([
        pl.len().alias("total_pessoas"),
        pl.col("paciente_idade").mean().alias("media_idade"),
        pl.col("paciente_idade").min().alias("menor_idade"),
        pl.col("paciente_idade").max().alias("maior_idade")
    ])
    .sort("media_idade", descending=True)
)

display(q_analise_categoria.collect())

shape: (3, 5)
┌────────────────┬───────────────┬─────────────┬─────────────┬─────────────┐
│ FAIXA_ETARIA   ┆ total_pessoas ┆ media_idade ┆ menor_idade ┆ maior_idade │
│ ---            ┆ ---           ┆ ---         ┆ ---         ┆ ---         │
│ str            ┆ u32           ┆ f64         ┆ i64         ┆ i64         │
╞════════════════╪═══════════════╪═════════════╪═════════════╪═════════════╡
│ Idoso          ┆ 7184787       ┆ 70.258031   ┆ 60          ┆ 222         │
│ Adulto         ┆ 19162730      ┆ 38.730442   ┆ 18          ┆ 59          │
│ Menor de Idade ┆ 4296636       ┆ 9.846166    ┆ -2          ┆ 17          │
└────────────────┴───────────────┴─────────────┴─────────────┴─────────────┘

In [7]:
# Pegar as primeiras 10 linhas
q_head = inicial.head(10)

# Pegar da linha 100 até a 150
q_meio = inicial.slice(100, 50)

display(q_head.collect())
display(q_meio.collect())

shape: (10, 32)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ document_ ┆ paciente_ ┆ paciente_ ┆ paciente_ ┆ … ┆ vacina_de ┆ vacina_co ┆ vacina_no ┆ sistema_ │
│ id        ┆ id        ┆ idade     ┆ dataNasci ┆   ┆ scricao_d ┆ digo      ┆ me        ┆ origem   │
│ ---       ┆ ---       ┆ ---       ┆ mento     ┆   ┆ ose       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ i64       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ str      │
│           ┆           ┆           ┆ date      ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ a235dbb4- ┆ 5d574f13b ┆ 32        ┆ 1989-05-2 ┆ … ┆ Reforço   ┆ 88        ┆ COVID-19  ┆ VACIVIDA │
│ 3391-419f ┆ 6065a3aa6 ┆           ┆ 9         ┆   ┆           ┆           ┆ JANSSEN - ┆          │
│ -bdf9-cfe ┆ 16b5b4757 ┆           ┆           ┆   ┆           ┆           ┆ Ad26.COV2 ┆          │
│ d14…      ┆ 50e…      ┆           ┆           ┆   ┆           ┆           ┆ .S        ┆          │
│ 90c1176e- ┆ 9fb17b039 ┆ 59        ┆ 1961-09-0 ┆ … ┆ 1ª Dose   ┆ 85        ┆ COVID-19  ┆ VACIVIDA │
│ 561b-4af4 ┆ bb026f66e ┆           ┆ 6         ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│ -8751-cea ┆ f1c21af1d ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│ ead…      ┆ ace…      ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
│ a2368077- ┆ b4462f225 ┆ 85        ┆ 1936-03-0 ┆ … ┆ Reforço   ┆ 87        ┆ COVID-19  ┆ VACIVIDA │
│ 7cfd-4421 ┆ ccdd46e27 ┆           ┆ 9         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -89a2-470 ┆ babc5da0e ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ e02…      ┆ c10…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 90c12c21- ┆ 60e8d202b ┆ 35        ┆ 1985-11-2 ┆ … ┆ 2ª Dose   ┆ 86        ┆ COVID-19  ┆ VACIVIDA │
│ e62b-4bbf ┆ 7d1874fe1 ┆           ┆ 2         ┆   ┆           ┆           ┆ SINOVAC/B ┆          │
│ -8e0b-a28 ┆ b92eaa665 ┆           ┆           ┆   ┆           ┆           ┆ UTANTAN - ┆          │
│ be8…      ┆ ed0…      ┆           ┆           ┆   ┆           ┆           ┆ CO…       ┆          │
│ a236e352- ┆ a143b41e6 ┆ 53        ┆ 1968-05-1 ┆ … ┆ 2ª Dose   ┆ 87        ┆ COVID-19  ┆ VACIVIDA │
│ a927-47bb ┆ 1d2f48d9c ┆           ┆ 8         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -970c-e43 ┆ cbdb456ec ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 2d0…      ┆ 68f…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 90c145a0- ┆ 2c597da79 ┆ 43        ┆ 1978-06-0 ┆ … ┆ 1ª Dose   ┆ 87        ┆ COVID-19  ┆ VACIVIDA │
│ 9e1c-402e ┆ b5f0866e1 ┆           ┆ 7         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -a4b2-4da ┆ cc87433c7 ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 788…      ┆ 73d…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ a237dcda- ┆ 1fffbc710 ┆ 14        ┆ 2007-09-1 ┆ … ┆ 2ª Dose   ┆ 87        ┆ COVID-19  ┆ VACIVIDA │
│ df10-4c15 ┆ a90f7fe24 ┆           ┆ 8         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -9e6f-528 ┆ a85709fc0 ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 6d9…      ┆ b06…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 90c1c326- ┆ e9a395d42 ┆ 58        ┆ 1964-06-1 ┆ … ┆ 2º        ┆ 85        ┆ COVID-19  ┆ VACIVIDA │
│ 8d00-4ebf ┆ c6c4bc0a1 ┆           ┆ 0         ┆   ┆ Reforço   ┆           ┆ ASTRAZENE ┆          │
│ -b171-6e2 ┆ 4c8dafba3 ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│ 66a…      ┆ 9be…      ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
│ a238024c- ┆ d7403958e ┆ 27        ┆ 1994-04-1 ┆ … ┆ Reforço   ┆ 87        ┆ COVID-19  ┆ VACIVIDA │
│ 6b7a-4e4d ┆ 4a4321409 ┆           ┆ 6         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -ac21-bc5 ┆ 1497020ba ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 497…      ┆ 5dc…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 90c24dc9- ┆ 359ac69ef ┆ 59        ┆ 1962-09-0 ┆ … ┆ Reforço   ┆ 87        ┆ COVID-19  ┆ VACIVIDA │
│ 22bd-47ca ┆ 3eb1493cd ┆           ┆ 7         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -83d5-10d ┆ 40d856db9 ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 6a5…      ┆ ee9…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

shape: (50, 32)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ document_ ┆ paciente_ ┆ paciente_ ┆ paciente_ ┆ … ┆ vacina_de ┆ vacina_co ┆ vacina_no ┆ sistema_ │
│ id        ┆ id        ┆ idade     ┆ dataNasci ┆   ┆ scricao_d ┆ digo      ┆ me        ┆ origem   │
│ ---       ┆ ---       ┆ ---       ┆ mento     ┆   ┆ ose       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ i64       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ str      │
│           ┆           ┆           ┆ date      ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ a249df23- ┆ ac9ca2419 ┆ 32        ┆ 1988-09-1 ┆ … ┆ 1ª Dose   ┆ 86        ┆ COVID-19  ┆ VACIVIDA │
│ ecf1-435d ┆ 82d574e04 ┆           ┆ 6         ┆   ┆           ┆           ┆ SINOVAC/B ┆          │
│ -bd01-a64 ┆ e6e0e23b5 ┆           ┆           ┆   ┆           ┆           ┆ UTANTAN - ┆          │
│ 418…      ┆ bd3…      ┆           ┆           ┆   ┆           ┆           ┆ CO…       ┆          │
│ 90d54c63- ┆ ea6619228 ┆ 64        ┆ 1957-04-0 ┆ … ┆ Reforço   ┆ 88        ┆ COVID-19  ┆ VACIVIDA │
│ f0b6-40b1 ┆ 00a7fb251 ┆           ┆ 8         ┆   ┆           ┆           ┆ JANSSEN - ┆          │
│ -9f84-ec5 ┆ c0918bdd3 ┆           ┆           ┆   ┆           ┆           ┆ Ad26.COV2 ┆          │
│ fd5…      ┆ 3e0…      ┆           ┆           ┆   ┆           ┆           ┆ .S        ┆          │
│ a24a7b00- ┆ b0f5ccd07 ┆ 48        ┆ 1972-10-1 ┆ … ┆ 2ª Dose   ┆ 87        ┆ COVID-19  ┆ VACIVIDA │
│ 227e-4e49 ┆ d80aa5592 ┆           ┆ 0         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -8276-731 ┆ fe19eb8a1 ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 9a3…      ┆ 707…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 90d5d993- ┆ 85ed5b181 ┆ 17        ┆ 2003-12-0 ┆ … ┆ 1ª Dose   ┆ 87        ┆ COVID-19  ┆ VACIVIDA │
│ 2368-4b06 ┆ 33b2b2175 ┆           ┆ 4         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -8932-f91 ┆ 1fbe78e2e ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ b5b…      ┆ 0a9…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ a24b89df- ┆ 91a06699a ┆ 57        ┆ 1964-09-2 ┆ … ┆ Reforço   ┆ 85        ┆ COVID-19  ┆ VACIVIDA │
│ 7fbb-46a1 ┆ a1fa6abd9 ┆           ┆ 1         ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│ -a906-938 ┆ 0200fc0e4 ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│ 571…      ┆ b82…      ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 90dce654- ┆ fea7a87cf ┆ 68        ┆ 1952-11-1 ┆ … ┆ Reforço   ┆ 87        ┆ COVID-19  ┆ VACIVIDA │
│ 38b7-46b5 ┆ f9cfae9a2 ┆           ┆ 0         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -9d48-6c2 ┆ 90c714cdf ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 9cd…      ┆ 290…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ a251e72a- ┆ 3fd3ad71c ┆ 19        ┆ 2002-07-0 ┆ … ┆ 2ª Dose   ┆ 86        ┆ COVID-19  ┆          │
│ 6a59-4335 ┆ 808d35c0f ┆           ┆ 5         ┆   ┆           ┆           ┆ SINOVAC/B ┆          │
│ -855d-7cb ┆ 5647e8fd4 ┆           ┆           ┆   ┆           ┆           ┆ UTANTAN - ┆          │
│ 2c3…      ┆ b9e…      ┆           ┆           ┆   ┆           ┆           ┆ CO…       ┆          │
│ 90dd01a4- ┆ 74d547b52 ┆ 43        ┆ 1978-02-2 ┆ … ┆ 2ª Dose   ┆ 85        ┆ COVID-19  ┆ VACIVIDA │
│ a9d3-46dd ┆ 0d691a265 ┆           ┆ 2         ┆   ┆           ┆           ┆ ASTRAZENE ┆          │
│ -8c01-bd8 ┆ 5c70deab3 ┆           ┆           ┆   ┆           ┆           ┆ CA/FIOCRU ┆          │
│ d3a…      ┆ a56…      ┆           ┆           ┆   ┆           ┆           ┆ Z -…      ┆          │
│ a252a05c- ┆ f8ac3d485 ┆ 12        ┆ 2010-02-0 ┆ … ┆ 2ª Dose   ┆ 87        ┆ COVID-19  ┆ VACIVIDA │
│ 9ffc-4349 ┆ c4b55e406 ┆           ┆ 3         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -a6ee-ed2 ┆ 447a910ab ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ a9c…      ┆ a2c…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 90dd24f8- ┆ f36b39417 ┆ 85        ┆ 1937-11-2 ┆ … ┆ Reforço   ┆ 103       ┆ COVID-19  ┆ VACIVIDA │
│ 9256-497a ┆ 978091c4f ┆           ┆ 1         ┆   ┆           ┆           ┆ PFIZER -  ┆          │
│ -8c3a-c31 ┆ a40cc8900 ┆           ┆           ┆   ┆           ┆           ┆ COMIRNATY ┆          │
│ 4cd…      ┆ b3a…      ┆           ┆           ┆   ┆           ┆           ┆ BI…       ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [8]:
# Recorte de linhas específicas
q_recorte_indices = (
    inicial
    .with_row_index("id_linha")
    .filter(pl.col("id_linha").is_in([0, 10, 50]))
    .select([
        "paciente_endereco_uf",
        "paciente_endereco_nmMunicipio"
    ])
)

display(q_recorte_indices.collect())

shape: (3, 2)
┌──────────────────────┬───────────────────────────────┐
│ paciente_endereco_uf ┆ paciente_endereco_nmMunicipio │
│ ---                  ┆ ---                           │
│ str                  ┆ str                           │
╞══════════════════════╪═══════════════════════════════╡
│ SP                   ┆ GUARULHOS                     │
│ SP                   ┆ SANTO ANDRE                   │
│ SP                   ┆ BROTAS                        │
└──────────────────────┴───────────────────────────────┘

In [9]:
q_stats_mun = (
    inicial.group_by("paciente_endereco_nmMunicipio")
    .agg([
        pl.len().alias("total_vacinados"),
        pl.col("paciente_idade").mean().alias("media_idade"),
        pl.col("paciente_idade").max().alias("maior_idade"),
        pl.col("paciente_endereco_uf").first().alias("uf_origem")
    ])
    .sort("total_vacinados", descending=True)
)

display(q_stats_mun.collect())

shape: (5_323, 5)
┌───────────────────────────────┬─────────────────┬─────────────┬─────────────┬───────────┐
│ paciente_endereco_nmMunicipio ┆ total_vacinados ┆ media_idade ┆ maior_idade ┆ uf_origem │
│ ---                           ┆ ---             ┆ ---         ┆ ---         ┆ ---       │
│ str                           ┆ u32             ┆ f64         ┆ i64         ┆ str       │
╞═══════════════════════════════╪═════════════════╪═════════════╪═════════════╪═══════════╡
│ SAO PAULO                     ┆ 8010895         ┆ 42.706369   ┆ 221         ┆ SP        │
│ GUARULHOS                     ┆ 896987          ┆ 39.929066   ┆ 121         ┆ SP        │
│ CAMPINAS                      ┆ 754323          ┆ 43.397731   ┆ 124         ┆ SP        │
│ SAO BERNARDO DO CAMPO         ┆ 534888          ┆ 42.327689   ┆ 129         ┆ SP        │
│ SANTO ANDRE                   ┆ 526428          ┆ 44.212181   ┆ 172         ┆ SP        │
│ …                             ┆ …               ┆ …           ┆ …           ┆ …         │
│ ALOANDIA                      ┆ 1               ┆ 89.0        ┆ 89          ┆ GO        │
│ LAGOA DOS TRES CANTOS         ┆ 1               ┆ 10.0        ┆ 10          ┆ RS        │
│ PINDAMONHANGABA SP            ┆ 1               ┆ 15.0        ┆ 15          ┆ None      │
│ SP                            ┆ 1               ┆ 8.0         ┆ 8           ┆ None      │
│ BRASIL                        ┆ 1               ┆ 9.0         ┆ 9           ┆           │
└───────────────────────────────┴─────────────────┴─────────────┴─────────────┴───────────┘

In [10]:
import polars as pl
import time

print("=== TESTE 1: Processamento SEM StringCache ===")
start_1 = time.time()

q_sem_cache = (
    pl.scan_parquet(r"C:\Users\diogo.durao\Documents\covid_sp.parquet")
    .with_columns(
        pl.col("paciente_idade").cast(pl.Int64, strict=False),
        pl.col("paciente_dataNascimento").str.to_date("%Y-%m-%d", strict=False),
        pl.col("vacina_dataAplicacao").str.to_date("%Y-%m-%d", strict=False)
    )
    .group_by(["paciente_endereco_uf", "paciente_endereco_nmMunicipio"])
    .agg([
        pl.col("paciente_idade").mean().alias("media_idade"),
        pl.col("paciente_idade").std().alias("desvio_idade")
    ])
    .sort("media_idade", descending=True)
)

df_1 = q_sem_cache.collect()
end_1 = time.time()
tempo_sem = end_1 - start_1

print(f"Tempo SEM Cache: {tempo_sem:.4f} segundos")
print(f"Uso de memória estimado (coluna UF): {df_1['paciente_endereco_uf'].estimated_size()} bytes\n")

display(df_1)

=== TESTE 1: Processamento SEM StringCache ===
Tempo SEM Cache: 5.8654 segundos
Uso de memória estimado (coluna UF): 11248 bytes

shape: (5_641, 4)
┌──────────────────────┬───────────────────────────────┬─────────────┬──────────────┐
│ paciente_endereco_uf ┆ paciente_endereco_nmMunicipio ┆ media_idade ┆ desvio_idade │
│ ---                  ┆ ---                           ┆ ---         ┆ ---          │
│ str                  ┆ str                           ┆ f64         ┆ f64          │
╞══════════════════════╪═══════════════════════════════╪═════════════╪══════════════╡
│                      ┆ carvillino                    ┆ 97.0        ┆ null         │
│ XX                   ┆ ESTRANGEIRO                   ┆ 94.0        ┆ null         │
│ TO                   ┆ ITAPORA DO TOCANTINS          ┆ 92.0        ┆ null         │
│ None                 ┆ JOSE BONIFACIO - SP           ┆ 89.5        ┆ 0.707107     │
│ GO                   ┆ ALOANDIA                      ┆ 89.0        ┆ null         │
│ …                    ┆ …                             ┆ …           ┆ …            │
│ SP                   ┆ Bengi                         ┆ 7.0         ┆ null         │
│ SC                   ┆ DONA EMMA                     ┆ 6.5         ┆ 4.949747     │
│ SP                   ┆ CENTRO                        ┆ 6.0         ┆ null         │
│ RS                   ┆ VISTA ALEGRE DO PRATA         ┆ 2.0         ┆ null         │
│ None                 ┆ WIEDENBORSTEL                 ┆ 0.0         ┆ null         │
└──────────────────────┴───────────────────────────────┴─────────────┴──────────────┘

In [11]:
print("=== TESTE 2: Processamento COM StringCache ===")

with pl.StringCache():
    start_2 = time.time()

    q_com_cache = (
        pl.scan_parquet(r"C:\Users\diogo.durao\Documents\covid_sp.parquet")
        .with_columns(
            pl.col("paciente_idade").cast(pl.Int64, strict=False),
            pl.col("paciente_dataNascimento").str.to_date("%Y-%m-%d", strict=False),
            pl.col("vacina_dataAplicacao").str.to_date("%Y-%m-%d", strict=False)
        )
        .group_by([
            "paciente_endereco_uf",
            "paciente_endereco_nmMunicipio"
        ])
        .agg([
            pl.col("paciente_idade").mean().alias("media_idade"),
            pl.col("paciente_idade").std().alias("desvio_idade")
        ])
        .sort("media_idade", descending=True)
    )

    df_2 = q_com_cache.collect()
    end_2 = time.time()

tempo_com = end_2 - start_2

print(f"Tempo COM Cache: {tempo_com:.4f} segundos")
print(f"Uso de memória estimado (coluna UF): {df_2['paciente_endereco_uf'].estimated_size()} bytes\n")

=== TESTE 2: Processamento COM StringCache ===
Tempo COM Cache: 6.8357 segundos
Uso de memória estimado (coluna UF): 11248 bytes